import { Place } from '../types';

export const PLACES: Place[] = [
  {
    id: 'besant-nagar-beach',
    name: 'Besant Nagar Beach',
    category: 'beaches',
    area: 'Besant Nagar',
    lat: 13.0002,
    lng: 80.2725,
    rating: 4.3,
    reviewCount: 12400,
    budget: 'free',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['chill', 'nature', 'romantic'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '05:00', close: '22:00' },
      sunday: { open: '05:00', close: '22:00' },
    },
    description: 'Popular beach with a calm vibe, great for evening walks and street food.',
    insiderTip: 'Head to the south end for fewer crowds. The sundal vendors near the parking lot are the OG.',
    googleMapsUrl: 'https://maps.google.com/?q=Besant+Nagar+Beach+Chennai',
    imageKeyword: 'besant-nagar-beach',
  },
  {
    id: 'marina-beach',
    name: 'Marina Beach',
    category: 'beaches',
    area: 'Mylapore',
    lat: 13.0500,
    lng: 80.2824,
    rating: 4.2,
    reviewCount: 45000,
    budget: 'free',
    avgTimeMinutes: 120,
    indoor: false,
    outdoor: true,
    vibes: ['chill', 'social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '05:00', close: '22:00' },
      sunday: { open: '05:00', close: '22:00' },
    },
    description: 'India\'s longest urban beach. Iconic Chennai landmark with food stalls and kite vendors.',
    insiderTip: 'Go early morning for the best sunrise. Evening gets very crowded on weekends.',
    googleMapsUrl: 'https://maps.google.com/?q=Marina+Beach+Chennai',
    imageKeyword: 'marina-beach',
  },
  {
    id: 'kapaleeshwarar-temple',
    name: 'Kapaleeshwarar Temple',
    category: 'temples-heritage',
    area: 'Mylapore',
    lat: 13.0337,
    lng: 80.2695,
    rating: 4.7,
    reviewCount: 18500,
    budget: 'free',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['cultural', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '20:00' },
      sunday: { open: '06:00', close: '20:00' },
    },
    description: 'Ancient Dravidian temple with stunning gopuram. The heart of Mylapore culture.',
    insiderTip: 'Visit during evening pooja (6 PM) for the best atmosphere. Temple street food after is a must.',
    googleMapsUrl: 'https://maps.google.com/?q=Kapaleeshwarar+Temple+Chennai',
    imageKeyword: 'kapaleeshwarar-temple',
  },
  {
    id: 'amethyst',
    name: 'Amethyst',
    category: 'cafes',
    area: 'Nungambakkam',
    lat: 13.0610,
    lng: 80.2460,
    rating: 4.5,
    reviewCount: 8200,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: true,
    vibes: ['romantic', 'artsy', 'chill'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:00', close: '23:00' },
      sunday: { open: '09:00', close: '23:00' },
    },
    description: 'Heritage bungalow turned cafe with a lush garden. One of Chennai\'s most beautiful spaces.',
    insiderTip: 'Grab a garden table and try the cold brew. Weekend brunch gets packed — go before 10 AM.',
    googleMapsUrl: 'https://maps.google.com/?q=Amethyst+Cafe+Chennai',
    imageKeyword: 'amethyst-cafe',
  },
  {
    id: 'phoenix-marketcity',
    name: 'Phoenix MarketCity',
    category: 'shopping',
    area: 'Velachery',
    lat: 12.9925,
    lng: 80.2165,
    rating: 4.3,
    reviewCount: 32000,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Chennai\'s biggest mall with movies, food court, bowling, and every brand you need.',
    insiderTip: 'Food court on 3rd floor has the best variety. Go after 6 PM on Saturday for the vibe.',
    googleMapsUrl: 'https://maps.google.com/?q=Phoenix+MarketCity+Chennai',
    imageKeyword: 'phoenix-marketcity',
  },
  {
    id: 'semmozhi-poonga',
    name: 'Semmozhi Poonga',
    category: 'parks',
    area: 'Nungambakkam',
    lat: 13.0590,
    lng: 80.2510,
    rating: 4.4,
    reviewCount: 9800,
    budget: 'free',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'chill', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '20:00' },
      sunday: { open: '06:00', close: '20:00' },
    },
    description: 'Beautiful botanical garden in the heart of the city. A green oasis with rare plants.',
    insiderTip: 'Morning walks here are magical. The butterfly garden section is the hidden gem.',
    googleMapsUrl: 'https://maps.google.com/?q=Semmozhi+Poonga+Chennai',
    imageKeyword: 'semmozhi-poonga',
  },
  {
    id: 'sowcarpet-food-walk',
    name: 'Sowcarpet Food Walk',
    category: 'street-food',
    area: 'Egmore',
    lat: 13.0930,
    lng: 80.2810,
    rating: 4.5,
    reviewCount: 5600,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['foodie', 'social', 'cultural'],
    groupTypes: ['couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Chennai\'s street food paradise. Jain and Gujarati food, chaats, sweets, and more.',
    insiderTip: 'Start at Mint Street. Try the Chinese bhel and the famous jigarthanda at the corner shop.',
    googleMapsUrl: 'https://maps.google.com/?q=Sowcarpet+Chennai',
    imageKeyword: 'sowcarpet-food',
  },
  {
    id: 'broken-bridge',
    name: 'Broken Bridge',
    category: 'photography',
    area: 'Adyar',
    lat: 13.0040,
    lng: 80.2710,
    rating: 4.3,
    reviewCount: 4200,
    budget: 'free',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'romantic', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '05:00', close: '19:00' },
      sunday: { open: '05:00', close: '19:00' },
    },
    description: 'Abandoned bridge over the Adyar estuary. Stunning sunset views and a photography hotspot.',
    insiderTip: 'Best at golden hour (5-6 PM). Wear shoes you don\'t mind getting muddy.',
    googleMapsUrl: 'https://maps.google.com/?q=Broken+Bridge+Adyar+Chennai',
    imageKeyword: 'broken-bridge-adyar',
  },
  {
    id: 'mystery-rooms',
    name: 'Mystery Rooms',
    category: 'sports-fun',
    area: 'Nungambakkam',
    lat: 13.0580,
    lng: 80.2380,
    rating: 4.4,
    reviewCount: 3100,
    budget: 'under-2000',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: false,
    vibes: ['adventure', 'social'],
    groupTypes: ['friends', 'couple'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Escape room experiences with multiple themed rooms. Great for groups who love puzzles.',
    insiderTip: 'Book the "Haunted Asylum" room — it\'s the hardest but most fun. Go with 4+ people.',
    googleMapsUrl: 'https://maps.google.com/?q=Mystery+Rooms+Chennai',
    imageKeyword: 'mystery-rooms',
  },
  {
    id: 'dakshinachitra',
    name: 'Dakshinachitra',
    category: 'art-museums',
    area: 'OMR',
    lat: 12.8150,
    lng: 80.2470,
    rating: 4.3,
    reviewCount: 7800,
    budget: 'under-500',
    avgTimeMinutes: 150,
    indoor: true,
    outdoor: true,
    vibes: ['cultural', 'artsy', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '18:00' },
      sunday: { open: '10:00', close: '18:00' },
    },
    description: 'Living museum of South Indian art, architecture, and crafts on the ECR.',
    insiderTip: 'Don\'t miss the pottery workshop. The traditional houses from Kerala section is incredible.',
    googleMapsUrl: 'https://maps.google.com/?q=Dakshinachitra+Chennai',
    imageKeyword: 'dakshinachitra',
  },
  {
    id: 'brew-room',
    name: 'The Brew Room',
    category: 'cafes',
    area: 'Mylapore',
    lat: 13.0340,
    lng: 80.2690,
    rating: 4.5,
    reviewCount: 3200,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: false,
    vibes: ['chill', 'social', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '08:00', close: '23:00' },
      sunday: { open: '08:00', close: '23:00' },
    },
    description: 'Specialty coffee haven in the heart of Mylapore. Great pour-overs and single origins.',
    insiderTip: 'Try the cold brew flight — 3 different beans. The upstairs seating is quieter.',
    googleMapsUrl: 'https://maps.google.com/?q=The+Brew+Room+Mylapore+Chennai',
    imageKeyword: 'brew-room-mylapore',
  },
  {
    id: 'chamiers-cafe',
    name: 'Chamiers Cafe',
    category: 'cafes',
    area: 'Adyar',
    lat: 13.0068,
    lng: 80.2530,
    rating: 4.4,
    reviewCount: 5800,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: true,
    vibes: ['chill', 'romantic', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:00', close: '22:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    description: 'Charming cafe in a colonial-era bungalow. Great pastries, bookshop upstairs.',
    insiderTip: 'The garden courtyard is magical in the evening. Pair a croissant with their house blend.',
    googleMapsUrl: 'https://maps.google.com/?q=Chamiers+Cafe+Chennai',
    imageKeyword: 'chamiers-cafe',
  },
  {
    id: 'ciclo-cafe',
    name: 'Ciclo Cafe',
    category: 'cafes',
    area: 'Adyar',
    lat: 13.0110,
    lng: 80.2490,
    rating: 4.3,
    reviewCount: 4100,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: true,
    vibes: ['social', 'artsy', 'chill'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '08:00', close: '23:00' },
      sunday: { open: '08:00', close: '23:00' },
    },
    description: 'Cycling-themed cafe with a hip vibe. Great coffee, board games, and weekend events.',
    insiderTip: 'They host open mic nights on some Saturdays. Ask about the cycling meetups.',
    googleMapsUrl: 'https://maps.google.com/?q=Ciclo+Cafe+Chennai',
    imageKeyword: 'ciclo-cafe',
  },
  {
    id: 'sandys-chocolate',
    name: 'Sandy\'s Chocolate Laboratory',
    category: 'cafes',
    area: 'Adyar',
    lat: 13.0058,
    lng: 80.2546,
    rating: 4.4,
    reviewCount: 6500,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['foodie', 'social', 'romantic'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '10:00', close: '23:00' },
    },
    description: 'Chocolate lover\'s paradise. Handcrafted desserts, shakes, and the famous death-by-chocolate.',
    insiderTip: 'The chocolate truffle cake is life-changing. Go after dinner as a dessert stop.',
    googleMapsUrl: 'https://maps.google.com/?q=Sandys+Chocolate+Laboratory+Chennai',
    imageKeyword: 'sandys-chocolate',
  },
  {
    id: 'writers-cafe',
    name: 'Writer\'s Cafe',
    category: 'cafes',
    area: 'T. Nagar',
    lat: 13.0410,
    lng: 80.2280,
    rating: 4.2,
    reviewCount: 2800,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: false,
    vibes: ['chill', 'artsy'],
    groupTypes: ['solo', 'couple'],
    openHours: {
      saturday: { open: '09:00', close: '22:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    description: 'Cozy book-themed cafe. Walls lined with books, perfect for a quiet afternoon.',
    insiderTip: 'Grab the window seat with the reading lamp. Their filter coffee is surprisingly great.',
    googleMapsUrl: 'https://maps.google.com/?q=Writers+Cafe+T+Nagar+Chennai',
    imageKeyword: 'writers-cafe',
  },
  {
    id: 'cafe-de-paris',
    name: 'Cafe De Paris',
    category: 'cafes',
    area: 'Nungambakkam',
    lat: 13.0550,
    lng: 80.2400,
    rating: 4.1,
    reviewCount: 2200,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['chill', 'romantic'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:00', close: '22:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    description: 'French-inspired bistro cafe with great crepes, quiches, and European coffee.',
    insiderTip: 'The crepe suzette is a must. Quiet on Sunday mornings — perfect for a date.',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+De+Paris+Nungambakkam+Chennai',
    imageKeyword: 'cafe-de-paris',
  },
  {
    id: 'tea-villa-cafe',
    name: 'Tea Villa Cafe',
    category: 'cafes',
    area: 'T. Nagar',
    lat: 13.0395,
    lng: 80.2310,
    rating: 4.2,
    reviewCount: 3400,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'chill', 'foodie'],
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '10:00', close: '23:00' },
    },
    description: 'Tea-focused cafe with 100+ varieties. Great snacks and a vibrant weekend crowd.',
    insiderTip: 'Try the Kashmiri Kahwa or the bubble tea. The loaded nachos are unreal.',
    googleMapsUrl: 'https://maps.google.com/?q=Tea+Villa+Cafe+T+Nagar+Chennai',
    imageKeyword: 'tea-villa-cafe',
  },
  {
    id: 'kovalam-beach',
    name: 'Kovalam Beach',
    category: 'beaches',
    area: 'OMR',
    lat: 12.7904,
    lng: 80.2511,
    rating: 4.4,
    reviewCount: 7200,
    budget: 'free',
    avgTimeMinutes: 180,
    indoor: false,
    outdoor: true,
    vibes: ['adventure', 'nature', 'romantic'],
    groupTypes: ['couple', 'friends'],
    openHours: {
      saturday: { open: '05:00', close: '20:00' },
      sunday: { open: '05:00', close: '20:00' },
    },
    description: 'Pristine beach on ECR, less crowded than city beaches. Great for surfing and swimming.',
    insiderTip: 'Go early morning for the cleanest water. The nearby shacks serve fresh fish fry.',
    googleMapsUrl: 'https://maps.google.com/?q=Kovalam+Beach+Chennai',
    imageKeyword: 'kovalam-beach',
  },
  {
    id: 'guindy-national-park',
    name: 'Guindy National Park',
    category: 'parks',
    area: 'Guindy',
    lat: 13.0040,
    lng: 80.2310,
    rating: 4.2,
    reviewCount: 8500,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'adventure', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '09:00', close: '17:30' },
      sunday: { open: '09:00', close: '17:30' },
    },
    description: 'One of the smallest national parks in India, right in the city. Deer, snakes, and birds.',
    insiderTip: 'Visit the Children\'s Park section if with kids. Spot blackbucks near the lake area.',
    googleMapsUrl: 'https://maps.google.com/?q=Guindy+National+Park+Chennai',
    imageKeyword: 'guindy-national-park',
  },
  {
    id: 'express-avenue',
    name: 'Express Avenue',
    category: 'shopping',
    area: 'Egmore',
    lat: 13.0580,
    lng: 80.2680,
    rating: 4.4,
    reviewCount: 28000,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Premium mall in the heart of Chennai. Movies, food court, bowling, and great brands.',
    insiderTip: 'Hit the food court on level 3 for variety. The PVR Gold screen is worth the splurge.',
    googleMapsUrl: 'https://maps.google.com/?q=Express+Avenue+Mall+Chennai',
    imageKeyword: 'express-avenue',
  },
  {
    id: 'mylapore-street-food',
    name: 'Mylapore Temple Street Food',
    category: 'street-food',
    area: 'Mylapore',
    lat: 13.0350,
    lng: 80.2700,
    rating: 4.3,
    reviewCount: 4800,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['foodie', 'cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '07:00', close: '22:00' },
      sunday: { open: '07:00', close: '22:00' },
    },
    description: 'Street food heaven around Kapaleeshwarar Temple. Dosas, bajjis, sundal, and sweets.',
    insiderTip: 'The evening bajji-bonda stalls near the temple tank are legendary. Try the rose milk.',
    googleMapsUrl: 'https://maps.google.com/?q=Mylapore+Temple+Street+Food+Chennai',
    imageKeyword: 'mylapore-street-food',
  },
];
