import { Place } from '../types';

export const PLACES: Place[] = [
  {
    id: 'besant-nagar-beach',
    name: 'Besant Nagar Beach',
    category: 'beaches',
    area: 'Besant Nagar',
    lat: 13.0002,
    lng: 80.2725,
    rating: 4.3,
    reviewCount: 12400,
    budget: 'free',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['chill', 'nature', 'romantic'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '05:00', close: '22:00' },
      sunday: { open: '05:00', close: '22:00' },
    },
    description: 'Popular beach with a calm vibe, great for evening walks and street food.',
    insiderTip: 'Head to the south end for fewer crowds. The sundal vendors near the parking lot are the OG.',
    googleMapsUrl: 'https://maps.google.com/?q=Besant+Nagar+Beach+Chennai',
    imageKeyword: 'besant-nagar-beach',
  },
  {
    id: 'marina-beach',
    name: 'Marina Beach',
    category: 'beaches',
    area: 'Mylapore',
    lat: 13.0500,
    lng: 80.2824,
    rating: 4.2,
    reviewCount: 45000,
    budget: 'free',
    avgTimeMinutes: 120,
    indoor: false,
    outdoor: true,
    vibes: ['chill', 'social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '05:00', close: '22:00' },
      sunday: { open: '05:00', close: '22:00' },
    },
    description: 'India\'s longest urban beach. Iconic Chennai landmark with food stalls and kite vendors.',
    insiderTip: 'Go early morning for the best sunrise. Evening gets very crowded on weekends.',
    googleMapsUrl: 'https://maps.google.com/?q=Marina+Beach+Chennai',
    imageKeyword: 'marina-beach',
  },
  {
    id: 'kapaleeshwarar-temple',
    name: 'Kapaleeshwarar Temple',
    category: 'temples-heritage',
    area: 'Mylapore',
    lat: 13.0337,
    lng: 80.2695,
    rating: 4.7,
    reviewCount: 18500,
    budget: 'free',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['cultural', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '20:00' },
      sunday: { open: '06:00', close: '20:00' },
    },
    description: 'Ancient Dravidian temple with stunning gopuram. The heart of Mylapore culture.',
    insiderTip: 'Visit during evening pooja (6 PM) for the best atmosphere. Temple street food after is a must.',
    googleMapsUrl: 'https://maps.google.com/?q=Kapaleeshwarar+Temple+Chennai',
    imageKeyword: 'kapaleeshwarar-temple',
  },
  {
    id: 'amethyst',
    name: 'Amethyst',
    category: 'cafes',
    area: 'Nungambakkam',
    lat: 13.0610,
    lng: 80.2460,
    rating: 4.5,
    reviewCount: 8200,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: true,
    vibes: ['romantic', 'artsy', 'chill'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:00', close: '23:00' },
      sunday: { open: '09:00', close: '23:00' },
    },
    description: 'Heritage bungalow turned cafe with a lush garden. One of Chennai\'s most beautiful spaces.',
    insiderTip: 'Grab a garden table and try the cold brew. Weekend brunch gets packed — go before 10 AM.',
    googleMapsUrl: 'https://maps.google.com/?q=Amethyst+Cafe+Chennai',
    imageKeyword: 'amethyst-cafe',
  },
  {
    id: 'phoenix-marketcity',
    name: 'Phoenix MarketCity',
    category: 'shopping',
    area: 'Velachery',
    lat: 12.9925,
    lng: 80.2165,
    rating: 4.3,
    reviewCount: 32000,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Chennai\'s biggest mall with movies, food court, bowling, and every brand you need.',
    insiderTip: 'Food court on 3rd floor has the best variety. Go after 6 PM on Saturday for the vibe.',
    googleMapsUrl: 'https://maps.google.com/?q=Phoenix+MarketCity+Chennai',
    imageKeyword: 'phoenix-marketcity',
  },
  {
    id: 'semmozhi-poonga',
    name: 'Semmozhi Poonga',
    category: 'parks',
    area: 'Nungambakkam',
    lat: 13.0590,
    lng: 80.2510,
    rating: 4.4,
    reviewCount: 9800,
    budget: 'free',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'chill', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '20:00' },
      sunday: { open: '06:00', close: '20:00' },
    },
    description: 'Beautiful botanical garden in the heart of the city. A green oasis with rare plants.',
    insiderTip: 'Morning walks here are magical. The butterfly garden section is the hidden gem.',
    googleMapsUrl: 'https://maps.google.com/?q=Semmozhi+Poonga+Chennai',
    imageKeyword: 'semmozhi-poonga',
  },
  {
    id: 'sowcarpet-food-walk',
    name: 'Sowcarpet Food Walk',
    category: 'street-food',
    area: 'Egmore',
    lat: 13.0930,
    lng: 80.2810,
    rating: 4.5,
    reviewCount: 5600,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['foodie', 'social', 'cultural'],
    groupTypes: ['couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Chennai\'s street food paradise. Jain and Gujarati food, chaats, sweets, and more.',
    insiderTip: 'Start at Mint Street. Try the Chinese bhel and the famous jigarthanda at the corner shop.',
    googleMapsUrl: 'https://maps.google.com/?q=Sowcarpet+Chennai',
    imageKeyword: 'sowcarpet-food',
  },
  {
    id: 'broken-bridge',
    name: 'Broken Bridge',
    category: 'photography',
    area: 'Adyar',
    lat: 13.0040,
    lng: 80.2710,
    rating: 4.3,
    reviewCount: 4200,
    budget: 'free',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'romantic', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '05:00', close: '19:00' },
      sunday: { open: '05:00', close: '19:00' },
    },
    description: 'Abandoned bridge over the Adyar estuary. Stunning sunset views and a photography hotspot.',
    insiderTip: 'Best at golden hour (5-6 PM). Wear shoes you don\'t mind getting muddy.',
    googleMapsUrl: 'https://maps.google.com/?q=Broken+Bridge+Adyar+Chennai',
    imageKeyword: 'broken-bridge-adyar',
  },
  {
    id: 'mystery-rooms',
    name: 'Mystery Rooms',
    category: 'sports-fun',
    area: 'Nungambakkam',
    lat: 13.0580,
    lng: 80.2380,
    rating: 4.4,
    reviewCount: 3100,
    budget: 'under-2000',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: false,
    vibes: ['adventure', 'social'],
    groupTypes: ['friends', 'couple'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Escape room experiences with multiple themed rooms. Great for groups who love puzzles.',
    insiderTip: 'Book the "Haunted Asylum" room — it\'s the hardest but most fun. Go with 4+ people.',
    googleMapsUrl: 'https://maps.google.com/?q=Mystery+Rooms+Chennai',
    imageKeyword: 'mystery-rooms',
  },
  {
    id: 'dakshinachitra',
    name: 'Dakshinachitra',
    category: 'art-museums',
    area: 'OMR',
    lat: 12.8150,
    lng: 80.2470,
    rating: 4.3,
    reviewCount: 7800,
    budget: 'under-500',
    avgTimeMinutes: 150,
    indoor: true,
    outdoor: true,
    vibes: ['cultural', 'artsy', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '18:00' },
      sunday: { open: '10:00', close: '18:00' },
    },
    description: 'Living museum of South Indian art, architecture, and crafts on the ECR.',
    insiderTip: 'Don\'t miss the pottery workshop. The traditional houses from Kerala section is incredible.',
    googleMapsUrl: 'https://maps.google.com/?q=Dakshinachitra+Chennai',
    imageKeyword: 'dakshinachitra',
  },
  {
    id: 'brew-room',
    name: 'The Brew Room',
    category: 'cafes',
    area: 'Mylapore',
    lat: 13.0340,
    lng: 80.2690,
    rating: 4.5,
    reviewCount: 3200,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: false,
    vibes: ['chill', 'social', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '08:00', close: '23:00' },
      sunday: { open: '08:00', close: '23:00' },
    },
    description: 'Specialty coffee haven in the heart of Mylapore. Great pour-overs and single origins.',
    insiderTip: 'Try the cold brew flight — 3 different beans. The upstairs seating is quieter.',
    googleMapsUrl: 'https://maps.google.com/?q=The+Brew+Room+Mylapore+Chennai',
    imageKeyword: 'brew-room-mylapore',
  },
  {
    id: 'chamiers-cafe',
    name: 'Chamiers Cafe',
    category: 'cafes',
    area: 'Adyar',
    lat: 13.0068,
    lng: 80.2530,
    rating: 4.4,
    reviewCount: 5800,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: true,
    vibes: ['chill', 'romantic', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:00', close: '22:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    description: 'Charming cafe in a colonial-era bungalow. Great pastries, bookshop upstairs.',
    insiderTip: 'The garden courtyard is magical in the evening. Pair a croissant with their house blend.',
    googleMapsUrl: 'https://maps.google.com/?q=Chamiers+Cafe+Chennai',
    imageKeyword: 'chamiers-cafe',
  },
  {
    id: 'ciclo-cafe',
    name: 'Ciclo Cafe',
    category: 'cafes',
    area: 'Adyar',
    lat: 13.0110,
    lng: 80.2490,
    rating: 4.3,
    reviewCount: 4100,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: true,
    vibes: ['social', 'artsy', 'chill'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '08:00', close: '23:00' },
      sunday: { open: '08:00', close: '23:00' },
    },
    description: 'Cycling-themed cafe with a hip vibe. Great coffee, board games, and weekend events.',
    insiderTip: 'They host open mic nights on some Saturdays. Ask about the cycling meetups.',
    googleMapsUrl: 'https://maps.google.com/?q=Ciclo+Cafe+Chennai',
    imageKeyword: 'ciclo-cafe',
  },
  {
    id: 'sandys-chocolate',
    name: 'Sandy\'s Chocolate Laboratory',
    category: 'cafes',
    area: 'Adyar',
    lat: 13.0058,
    lng: 80.2546,
    rating: 4.4,
    reviewCount: 6500,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['foodie', 'social', 'romantic'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '10:00', close: '23:00' },
    },
    description: 'Chocolate lover\'s paradise. Handcrafted desserts, shakes, and the famous death-by-chocolate.',
    insiderTip: 'The chocolate truffle cake is life-changing. Go after dinner as a dessert stop.',
    googleMapsUrl: 'https://maps.google.com/?q=Sandys+Chocolate+Laboratory+Chennai',
    imageKeyword: 'sandys-chocolate',
  },
  {
    id: 'writers-cafe',
    name: 'Writer\'s Cafe',
    category: 'cafes',
    area: 'T. Nagar',
    lat: 13.0410,
    lng: 80.2280,
    rating: 4.2,
    reviewCount: 2800,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: false,
    vibes: ['chill', 'artsy'],
    groupTypes: ['solo', 'couple'],
    openHours: {
      saturday: { open: '09:00', close: '22:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    description: 'Cozy book-themed cafe. Walls lined with books, perfect for a quiet afternoon.',
    insiderTip: 'Grab the window seat with the reading lamp. Their filter coffee is surprisingly great.',
    googleMapsUrl: 'https://maps.google.com/?q=Writers+Cafe+T+Nagar+Chennai',
    imageKeyword: 'writers-cafe',
  },
  {
    id: 'cafe-de-paris',
    name: 'Cafe De Paris',
    category: 'cafes',
    area: 'Nungambakkam',
    lat: 13.0550,
    lng: 80.2400,
    rating: 4.1,
    reviewCount: 2200,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['chill', 'romantic'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:00', close: '22:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    description: 'French-inspired bistro cafe with great crepes, quiches, and European coffee.',
    insiderTip: 'The crepe suzette is a must. Quiet on Sunday mornings — perfect for a date.',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+De+Paris+Nungambakkam+Chennai',
    imageKeyword: 'cafe-de-paris',
  },
  {
    id: 'tea-villa-cafe',
    name: 'Tea Villa Cafe',
    category: 'cafes',
    area: 'T. Nagar',
    lat: 13.0395,
    lng: 80.2310,
    rating: 4.2,
    reviewCount: 3400,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'chill', 'foodie'],
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '10:00', close: '23:00' },
    },
    description: 'Tea-focused cafe with 100+ varieties. Great snacks and a vibrant weekend crowd.',
    insiderTip: 'Try the Kashmiri Kahwa or the bubble tea. The loaded nachos are unreal.',
    googleMapsUrl: 'https://maps.google.com/?q=Tea+Villa+Cafe+T+Nagar+Chennai',
    imageKeyword: 'tea-villa-cafe',
  },
  {
    id: 'kovalam-beach',
    name: 'Kovalam Beach',
    category: 'beaches',
    area: 'OMR',
    lat: 12.7904,
    lng: 80.2511,
    rating: 4.4,
    reviewCount: 7200,
    budget: 'free',
    avgTimeMinutes: 180,
    indoor: false,
    outdoor: true,
    vibes: ['adventure', 'nature', 'romantic'],
    groupTypes: ['couple', 'friends'],
    openHours: {
      saturday: { open: '05:00', close: '20:00' },
      sunday: { open: '05:00', close: '20:00' },
    },
    description: 'Pristine beach on ECR, less crowded than city beaches. Great for surfing and swimming.',
    insiderTip: 'Go early morning for the cleanest water. The nearby shacks serve fresh fish fry.',
    googleMapsUrl: 'https://maps.google.com/?q=Kovalam+Beach+Chennai',
    imageKeyword: 'kovalam-beach',
  },
  {
    id: 'guindy-national-park',
    name: 'Guindy National Park',
    category: 'parks',
    area: 'Guindy',
    lat: 13.0040,
    lng: 80.2310,
    rating: 4.2,
    reviewCount: 8500,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'adventure', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '09:00', close: '17:30' },
      sunday: { open: '09:00', close: '17:30' },
    },
    description: 'One of the smallest national parks in India, right in the city. Deer, snakes, and birds.',
    insiderTip: 'Visit the Children\'s Park section if with kids. Spot blackbucks near the lake area.',
    googleMapsUrl: 'https://maps.google.com/?q=Guindy+National+Park+Chennai',
    imageKeyword: 'guindy-national-park',
  },
  {
    id: 'express-avenue',
    name: 'Express Avenue',
    category: 'shopping',
    area: 'Egmore',
    lat: 13.0580,
    lng: 80.2680,
    rating: 4.4,
    reviewCount: 28000,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Premium mall in the heart of Chennai. Movies, food court, bowling, and great brands.',
    insiderTip: 'Hit the food court on level 3 for variety. The PVR Gold screen is worth the splurge.',
    googleMapsUrl: 'https://maps.google.com/?q=Express+Avenue+Mall+Chennai',
    imageKeyword: 'express-avenue',
  },
  {
    id: 'mylapore-street-food',
    name: 'Mylapore Temple Street Food',
    category: 'street-food',
    area: 'Mylapore',
    lat: 13.0350,
    lng: 80.2700,
    rating: 4.3,
    reviewCount: 4800,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['foodie', 'cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '07:00', close: '22:00' },
      sunday: { open: '07:00', close: '22:00' },
    },
    description: 'Street food heaven around Kapaleeshwarar Temple. Dosas, bajjis, sundal, and sweets.',
    insiderTip: 'The evening bajji-bonda stalls near the temple tank are legendary. Try the rose milk.',
    googleMapsUrl: 'https://maps.google.com/?q=Mylapore+Temple+Street+Food+Chennai',
    imageKeyword: 'mylapore-street-food',
  },
  {
    id: 'illusions-the-madras-pub',
    name: 'Illusions - The Madras Pub',
    category: 'cafes',
    area: 'Velachery',
    lat: 12.9790,
    lng: 80.2200,
    rating: 4.2,
    reviewCount: 3900,
    budget: 'under-2000',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'chill', 'foodie'],
    groupTypes: ['friends', 'couple'],
    openHours: {
      saturday: { open: '12:00', close: '23:30' },
      sunday: { open: '12:00', close: '23:30' },
    },
    description: 'Lively pub with great cocktails, live music on weekends, and solid bar food.',
    insiderTip: 'Go on Saturday night for the live band. The chicken wings and nachos are elite.',
    googleMapsUrl: 'https://maps.google.com/?q=Illusions+The+Madras+Pub+Chennai',
    imageKeyword: 'illusions-pub',
  },
  {
    id: 'the-flying-elephant',
    name: 'The Flying Elephant',
    category: 'cafes',
    area: 'Guindy',
    lat: 13.0100,
    lng: 80.2230,
    rating: 4.3,
    reviewCount: 4500,
    budget: 'under-2000',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['foodie', 'social', 'romantic'],
    groupTypes: ['couple', 'friends'],
    openHours: {
      saturday: { open: '12:00', close: '23:00' },
      sunday: { open: '12:00', close: '23:00' },
    },
    description: 'Multi-level restaurant at Park Hyatt. Asian, European, and Indian live kitchens under one roof.',
    insiderTip: 'The Sunday brunch is legendary. Book in advance — it fills up fast. Try the sushi counter.',
    googleMapsUrl: 'https://maps.google.com/?q=The+Flying+Elephant+Park+Hyatt+Chennai',
    imageKeyword: 'flying-elephant',
  },
  {
    id: 'bay-146',
    name: 'Bay 146',
    category: 'cafes',
    area: 'Besant Nagar',
    lat: 13.0005,
    lng: 80.2700,
    rating: 4.1,
    reviewCount: 2600,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: true,
    vibes: ['chill', 'romantic', 'social'],
    groupTypes: ['couple', 'friends'],
    openHours: {
      saturday: { open: '11:00', close: '23:00' },
      sunday: { open: '11:00', close: '23:00' },
    },
    description: 'Beachside cafe near Elliot\'s Beach. Chill vibes, sea breeze, and good comfort food.',
    insiderTip: 'Grab the outdoor table at sunset. Their milkshakes are the real deal.',
    googleMapsUrl: 'https://maps.google.com/?q=Bay+146+Besant+Nagar+Chennai',
    imageKeyword: 'bay-146',
  },
  {
    id: 'murugan-idli-shop',
    name: 'Murugan Idli Shop',
    category: 'street-food',
    area: 'T. Nagar',
    lat: 13.0425,
    lng: 80.2345,
    rating: 4.6,
    reviewCount: 22000,
    budget: 'under-500',
    avgTimeMinutes: 45,
    indoor: true,
    outdoor: false,
    vibes: ['foodie', 'cultural', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '22:30' },
      sunday: { open: '06:00', close: '22:30' },
    },
    description: 'Legendary idli chain. Fluffy idlis, crispy dosas, and the iconic ghee podi combo.',
    insiderTip: 'The ghee podi idli is non-negotiable. Go before 8 AM to avoid the queue.',
    googleMapsUrl: 'https://maps.google.com/?q=Murugan+Idli+Shop+T+Nagar+Chennai',
    imageKeyword: 'murugan-idli',
  },
  {
    id: 'junior-kuppanna',
    name: 'Junior Kuppanna',
    category: 'street-food',
    area: 'Egmore',
    lat: 13.0720,
    lng: 80.2600,
    rating: 4.4,
    reviewCount: 15000,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['foodie', 'social'],
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '11:30', close: '23:00' },
      sunday: { open: '11:30', close: '23:00' },
    },
    description: 'Chettinad cuisine at its finest. Fiery curries, biryani, and the famous mud pot chicken.',
    insiderTip: 'The Nandu (crab) Rasam is a must-try. Go for lunch — dinner queues are brutal.',
    googleMapsUrl: 'https://maps.google.com/?q=Junior+Kuppanna+Egmore+Chennai',
    imageKeyword: 'junior-kuppanna',
  },
  {
    id: 'marina-food-stalls',
    name: 'Marina Beach Food Stalls',
    category: 'street-food',
    area: 'Mylapore',
    lat: 13.0490,
    lng: 80.2810,
    rating: 4.0,
    reviewCount: 8900,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['foodie', 'social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '16:00', close: '22:00' },
      sunday: { open: '16:00', close: '22:00' },
    },
    description: 'Iconic beach-side street food. Corn, sundal, bajji, murukku, ice cream — the full Chennai experience.',
    insiderTip: 'The rose milk and badam milk vendors near the lighthouse end are the best.',
    googleMapsUrl: 'https://maps.google.com/?q=Marina+Beach+Food+Stalls+Chennai',
    imageKeyword: 'marina-food-stalls',
  },
  {
    id: 'besant-nagar-food-street',
    name: 'Besant Nagar Food Street',
    category: 'street-food',
    area: 'Besant Nagar',
    lat: 13.0010,
    lng: 80.2690,
    rating: 4.2,
    reviewCount: 5200,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['foodie', 'social'],
    groupTypes: ['couple', 'friends'],
    openHours: {
      saturday: { open: '16:00', close: '23:00' },
      sunday: { open: '16:00', close: '23:00' },
    },
    description: 'Food stalls and small eateries along the beach road. Shawarma, momos, and ice cream galore.',
    insiderTip: 'The shawarma near the 2nd cross signal is the OG. Pair it with a thick shake from next door.',
    googleMapsUrl: 'https://maps.google.com/?q=Besant+Nagar+Food+Street+Chennai',
    imageKeyword: 'besant-nagar-food',
  },
  {
    id: 'naturally-auroville',
    name: 'Naturally Auroville',
    category: 'cafes',
    area: 'Adyar',
    lat: 13.0075,
    lng: 80.2560,
    rating: 4.3,
    reviewCount: 1800,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['chill', 'nature', 'artsy'],
    groupTypes: ['solo', 'couple'],
    openHours: {
      saturday: { open: '09:00', close: '21:00' },
      sunday: { open: '09:00', close: '21:00' },
    },
    description: 'Organic cafe and store. Fresh salads, smoothie bowls, and wholesome baked goods.',
    insiderTip: 'Try the avocado toast and the kombucha. Great for a healthy brunch.',
    googleMapsUrl: 'https://maps.google.com/?q=Naturally+Auroville+Adyar+Chennai',
    imageKeyword: 'naturally-auroville',
  },
  {
    id: 'thalapakattu-biryani',
    name: 'Dindigul Thalappakatti Biryani',
    category: 'street-food',
    area: 'T. Nagar',
    lat: 13.0430,
    lng: 80.2350,
    rating: 4.3,
    reviewCount: 18000,
    budget: 'under-500',
    avgTimeMinutes: 45,
    indoor: true,
    outdoor: false,
    vibes: ['foodie'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '11:00', close: '23:00' },
      sunday: { open: '11:00', close: '23:00' },
    },
    description: 'Legendary Dindigul-style biryani. Seeraga samba rice, tender meat, and explosive flavour.',
    insiderTip: 'Order the mutton biryani with a side of brinjal curry. Skip the starters — go straight for biryani.',
    googleMapsUrl: 'https://maps.google.com/?q=Thalappakatti+Biryani+T+Nagar+Chennai',
    imageKeyword: 'thalappakatti-biryani',
  },
  {
    id: 'fort-st-george',
    name: 'Fort St. George',
    category: 'temples-heritage',
    area: 'Egmore',
    lat: 13.0800,
    lng: 80.2878,
    rating: 4.2,
    reviewCount: 9500,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['cultural', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '09:00', close: '17:00' },
      sunday: { open: '09:00', close: '17:00' },
    },
    description: 'First English fortress in India (1644). Fort museum, St. Mary\'s Church, and colonial history.',
    insiderTip: 'The fort museum has original letters from Clive and Cornwallis. Photography is free inside.',
    googleMapsUrl: 'https://maps.google.com/?q=Fort+St+George+Chennai',
    imageKeyword: 'fort-st-george',
  },
  {
    id: 'san-thome-cathedral',
    name: 'San Thome Cathedral',
    category: 'temples-heritage',
    area: 'Mylapore',
    lat: 13.0326,
    lng: 80.2778,
    rating: 4.5,
    reviewCount: 11000,
    budget: 'free',
    avgTimeMinutes: 45,
    indoor: true,
    outdoor: true,
    vibes: ['cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '20:00' },
      sunday: { open: '06:00', close: '20:00' },
    },
    description: 'Gothic cathedral built over the tomb of St. Thomas the Apostle. Stunning architecture.',
    insiderTip: 'The underground tomb chapel is hauntingly beautiful. Visit at sunset for the best light.',
    googleMapsUrl: 'https://maps.google.com/?q=San+Thome+Cathedral+Chennai',
    imageKeyword: 'san-thome-cathedral',
  },
  {
    id: 'government-museum',
    name: 'Government Museum Egmore',
    category: 'art-museums',
    area: 'Egmore',
    lat: 13.0694,
    lng: 80.2570,
    rating: 4.1,
    reviewCount: 7200,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['cultural', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '09:30', close: '17:00' },
      sunday: { open: '09:30', close: '17:00' },
    },
    description: 'Second oldest museum in India. Bronze gallery, archaeology, and natural history wings.',
    insiderTip: 'The Chola bronze gallery is world-class — don\'t skip it. Allow 2 hours minimum.',
    googleMapsUrl: 'https://maps.google.com/?q=Government+Museum+Egmore+Chennai',
    imageKeyword: 'government-museum-egmore',
  },
  {
    id: 'vr-chennai',
    name: 'VR Chennai',
    category: 'shopping',
    area: 'Anna Nagar',
    lat: 13.0920,
    lng: 80.2120,
    rating: 4.5,
    reviewCount: 25000,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Premium mall in Anna Nagar. Great food court, IMAX, high-end stores, and rooftop dining.',
    insiderTip: 'The IMAX screen here is the best in Chennai. The rooftop restaurants have great views.',
    googleMapsUrl: 'https://maps.google.com/?q=VR+Chennai+Anna+Nagar',
    imageKeyword: 'vr-chennai',
  },
  {
    id: 't-nagar-ranganathan',
    name: 'T. Nagar Ranganathan Street',
    category: 'shopping',
    area: 'T. Nagar',
    lat: 13.0400,
    lng: 80.2340,
    rating: 4.2,
    reviewCount: 15000,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: false,
    outdoor: true,
    vibes: ['social', 'cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '09:00', close: '21:30' },
      sunday: { open: '09:00', close: '21:30' },
    },
    description: 'Chennai\'s busiest shopping street. Sarees, jewellery, textiles, and street shopping galore.',
    insiderTip: 'Go early morning (before 10 AM) to avoid the insane crowds. Bargain hard at street stalls.',
    googleMapsUrl: 'https://maps.google.com/?q=Ranganathan+Street+T+Nagar+Chennai',
    imageKeyword: 'ranganathan-street',
  },
  {
    id: 'cholamandal-artists',
    name: 'Cholamandal Artists\' Village',
    category: 'art-museums',
    area: 'Thiruvanmiyur',
    lat: 12.9540,
    lng: 80.2540,
    rating: 4.3,
    reviewCount: 3200,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: true,
    vibes: ['artsy', 'cultural'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:30', close: '18:00' },
      sunday: { open: '09:30', close: '18:00' },
    },
    description: 'India\'s largest self-supporting artists\' commune. Galleries, sculptures, and live art.',
    insiderTip: 'Talk to the resident artists — many are happy to show their studios. Buy art directly.',
    googleMapsUrl: 'https://maps.google.com/?q=Cholamandal+Artists+Village+Chennai',
    imageKeyword: 'cholamandal-village',
  },
  {
    id: 'birla-planetarium',
    name: 'Birla Planetarium',
    category: 'art-museums',
    area: 'Guindy',
    lat: 13.0130,
    lng: 80.2340,
    rating: 4.1,
    reviewCount: 6800,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['family', 'cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '17:30' },
      sunday: { open: '10:00', close: '17:30' },
    },
    description: 'Dome-shaped planetarium with sky shows. Great for kids and space enthusiasts.',
    insiderTip: 'Catch the 3:30 PM English show — it\'s the best one. Combine with Guindy Park next door.',
    googleMapsUrl: 'https://maps.google.com/?q=Birla+Planetarium+Chennai',
    imageKeyword: 'birla-planetarium',
  },
  {
    id: 'covelong-surf',
    name: 'Covelong Point Surf School',
    category: 'sports-fun',
    area: 'OMR',
    lat: 12.7830,
    lng: 80.2560,
    rating: 4.5,
    reviewCount: 2800,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: false,
    outdoor: true,
    vibes: ['adventure', 'nature'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '06:00', close: '18:00' },
      sunday: { open: '06:00', close: '18:00' },
    },
    description: 'Learn surfing on the ECR! Beginner-friendly waves, board rental, and certified instructors.',
    insiderTip: 'Book the 7 AM slot for the best waves and fewer people. They provide everything.',
    googleMapsUrl: 'https://maps.google.com/?q=Covelong+Point+Surf+School+Chennai',
    imageKeyword: 'covelong-surf',
  },
  {
    id: 'dugout-trampoline',
    name: 'Dugout Trampoline Park',
    category: 'sports-fun',
    area: 'OMR',
    lat: 12.9350,
    lng: 80.2290,
    rating: 4.3,
    reviewCount: 4200,
    budget: 'under-2000',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['adventure', 'social', 'family'],
    groupTypes: ['friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '21:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    description: 'Massive trampoline park with foam pits, dodgeball courts, and ninja obstacle courses.',
    insiderTip: 'Wear grip socks (they sell them there). Book the 2-hour package — 1 hour flies by.',
    googleMapsUrl: 'https://maps.google.com/?q=Dugout+Trampoline+Park+OMR+Chennai',
    imageKeyword: 'dugout-trampoline',
  },
  {
    id: 'ashtalakshmi-temple',
    name: 'Ashtalakshmi Temple',
    category: 'temples-heritage',
    area: 'Besant Nagar',
    lat: 13.0005,
    lng: 80.2720,
    rating: 4.4,
    reviewCount: 8700,
    budget: 'free',
    avgTimeMinutes: 45,
    indoor: false,
    outdoor: true,
    vibes: ['cultural', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:30', close: '12:00' },
      sunday: { open: '06:30', close: '12:00' },
    },
    description: 'Beautiful seaside temple dedicated to eight forms of Lakshmi. Stunning ocean views.',
    insiderTip: 'Visit at sunrise for an unforgettable experience. Combine with Elliot\'s Beach walk after.',
    googleMapsUrl: 'https://maps.google.com/?q=Ashtalakshmi+Temple+Chennai',
    imageKeyword: 'ashtalakshmi-temple',
  },
  {
    id: 'marundeeswarar-temple',
    name: 'Marundeeswarar Temple',
    category: 'temples-heritage',
    area: 'Thiruvanmiyur',
    lat: 12.9842,
    lng: 80.2597,
    rating: 4.6,
    reviewCount: 6500,
    budget: 'free',
    avgTimeMinutes: 45,
    indoor: false,
    outdoor: true,
    vibes: ['cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '05:30', close: '12:30' },
      sunday: { open: '05:30', close: '12:30' },
    },
    description: 'Ancient Shiva temple known as the "temple of healing." Beautiful Dravidian architecture.',
    insiderTip: 'The temple tank area is peaceful. Visit early morning for the best darshan without crowds.',
    googleMapsUrl: 'https://maps.google.com/?q=Marundeeswarar+Temple+Thiruvanmiyur+Chennai',
    imageKeyword: 'marundeeswarar-temple',
  },
  {
    id: 'thiruvalluvar-beach',
    name: 'Thiruvalluvar Nagar Beach',
    category: 'beaches',
    area: 'Thiruvanmiyur',
    lat: 12.9870,
    lng: 80.2680,
    rating: 4.0,
    reviewCount: 2100,
    budget: 'free',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['chill', 'nature'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '05:00', close: '21:00' },
      sunday: { open: '05:00', close: '21:00' },
    },
    description: 'Quieter alternative to Besant Nagar beach. Locals\' secret for peaceful evening walks.',
    insiderTip: 'Much less crowded than Elliot\'s. Best on weekday evenings but still calm on weekends.',
    googleMapsUrl: 'https://maps.google.com/?q=Thiruvalluvar+Nagar+Beach+Chennai',
    imageKeyword: 'thiruvalluvar-beach',
  },
  {
    id: 'triplicane-biryani',
    name: 'Triplicane Biryani Street',
    category: 'street-food',
    area: 'Egmore',
    lat: 13.0570,
    lng: 80.2760,
    rating: 4.4,
    reviewCount: 6800,
    budget: 'under-500',
    avgTimeMinutes: 45,
    indoor: true,
    outdoor: true,
    vibes: ['foodie'],
    groupTypes: ['solo', 'friends'],
    openHours: {
      saturday: { open: '11:00', close: '23:00' },
      sunday: { open: '11:00', close: '23:00' },
    },
    description: 'Old Madras biryani hub. Multiple legendary joints serving Chennai\'s finest biryani since decades.',
    insiderTip: 'Star Biryani and Pakoda Corner are the local favourites. Go for lunch — sells out by 2 PM.',
    googleMapsUrl: 'https://maps.google.com/?q=Triplicane+Biryani+Chennai',
    imageKeyword: 'triplicane-biryani',
  },
];
