import { Place } from '../types';

export const PLACES: Place[] = [
  {
    id: 'besant-nagar-beach',
    name: 'Besant Nagar Beach',
    category: 'beaches',
    area: 'Besant Nagar',
    lat: 13.0002,
    lng: 80.2725,
    rating: 4.3,
    reviewCount: 12400,
    budget: 'free',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['chill', 'nature', 'romantic'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '05:00', close: '22:00' },
      sunday: { open: '05:00', close: '22:00' },
    },
    description: 'Popular beach with a calm vibe, great for evening walks and street food.',
    insiderTip: 'Head to the south end for fewer crowds. The sundal vendors near the parking lot are the OG.',
    googleMapsUrl: 'https://maps.google.com/?q=Besant+Nagar+Beach+Chennai',
    imageKeyword: 'besant-nagar-beach',
    photoUrl: '/api/photo?q=Besant+Nagar+Beach',
    googleSearchUrl: 'https://www.google.com/search?q=Besant+Nagar+Beach+Chennai',
  },
  {
    id: 'marina-beach',
    name: 'Marina Beach',
    category: 'beaches',
    area: 'Mylapore',
    lat: 13.0500,
    lng: 80.2824,
    rating: 4.2,
    reviewCount: 45000,
    budget: 'free',
    avgTimeMinutes: 120,
    indoor: false,
    outdoor: true,
    vibes: ['chill', 'social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '05:00', close: '22:00' },
      sunday: { open: '05:00', close: '22:00' },
    },
    description: 'India\'s longest urban beach. Iconic Chennai landmark with food stalls and kite vendors.',
    insiderTip: 'Go early morning for the best sunrise. Evening gets very crowded on weekends.',
    googleMapsUrl: 'https://maps.google.com/?q=Marina+Beach+Chennai',
    imageKeyword: 'marina-beach',
    photoUrl: '/api/photo?q=Marina+Beach+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Marina+Beach+Chennai',
  },
  {
    id: 'kapaleeshwarar-temple',
    name: 'Kapaleeshwarar Temple',
    category: 'temples-heritage',
    area: 'Mylapore',
    lat: 13.0337,
    lng: 80.2695,
    rating: 4.7,
    reviewCount: 18500,
    budget: 'free',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['cultural', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '20:00' },
      sunday: { open: '06:00', close: '20:00' },
    },
    description: 'Ancient Dravidian temple with stunning gopuram. The heart of Mylapore culture.',
    insiderTip: 'Visit during evening pooja (6 PM) for the best atmosphere. Temple street food after is a must.',
    googleMapsUrl: 'https://maps.google.com/?q=Kapaleeshwarar+Temple+Chennai',
    imageKeyword: 'kapaleeshwarar-temple',
    photoUrl: '/api/photo?q=Kapaleeshwarar+Temple',
    googleSearchUrl: 'https://www.google.com/search?q=Kapaleeshwarar+Temple+Chennai',
  },
  {
    id: 'amethyst',
    name: 'Amethyst',
    category: 'cafes',
    area: 'Nungambakkam',
    lat: 13.0610,
    lng: 80.2460,
    rating: 4.5,
    reviewCount: 8200,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: true,
    vibes: ['romantic', 'artsy', 'chill'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:00', close: '23:00' },
      sunday: { open: '09:00', close: '23:00' },
    },
    description: 'Heritage bungalow turned cafe with a lush garden. One of Chennai\'s most beautiful spaces.',
    insiderTip: 'Grab a garden table and try the cold brew. Weekend brunch gets packed — go before 10 AM.',
    googleMapsUrl: 'https://maps.google.com/?q=Amethyst+Cafe+Chennai',
    imageKeyword: 'amethyst-cafe',
    photoUrl: 'https://images.pexels.com/photos/28704256/pexels-photo-28704256.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Amethyst+Chennai',
  },
  {
    id: 'phoenix-marketcity',
    name: 'Phoenix MarketCity',
    category: 'shopping',
    area: 'Velachery',
    lat: 12.9925,
    lng: 80.2165,
    rating: 4.3,
    reviewCount: 32000,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Chennai\'s biggest mall with movies, food court, bowling, and every brand you need.',
    insiderTip: 'Food court on 3rd floor has the best variety. Go after 6 PM on Saturday for the vibe.',
    googleMapsUrl: 'https://maps.google.com/?q=Phoenix+MarketCity+Chennai',
    imageKeyword: 'phoenix-marketcity',
    photoUrl: '/api/photo?q=Phoenix+MarketCity+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Phoenix+MarketCity+Chennai',
  },
  {
    id: 'semmozhi-poonga',
    name: 'Semmozhi Poonga',
    category: 'parks',
    area: 'Nungambakkam',
    lat: 13.0590,
    lng: 80.2510,
    rating: 4.4,
    reviewCount: 9800,
    budget: 'free',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'chill', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '20:00' },
      sunday: { open: '06:00', close: '20:00' },
    },
    description: 'Beautiful botanical garden in the heart of the city. A green oasis with rare plants.',
    insiderTip: 'Morning walks here are magical. The butterfly garden section is the hidden gem.',
    googleMapsUrl: 'https://maps.google.com/?q=Semmozhi+Poonga+Chennai',
    imageKeyword: 'semmozhi-poonga',
    photoUrl: '/api/photo?q=Semmozhi+Poonga',
    googleSearchUrl: 'https://www.google.com/search?q=Semmozhi+Poonga+Chennai',
  },
  {
    id: 'sowcarpet-food-walk',
    name: 'Sowcarpet Food Walk',
    category: 'street-food',
    area: 'Egmore',
    lat: 13.0930,
    lng: 80.2810,
    rating: 4.5,
    reviewCount: 5600,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['foodie', 'social', 'cultural'],
    groupTypes: ['couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Chennai\'s street food paradise. Jain and Gujarati food, chaats, sweets, and more.',
    insiderTip: 'Start at Mint Street. Try the Chinese bhel and the famous jigarthanda at the corner shop.',
    googleMapsUrl: 'https://maps.google.com/?q=Sowcarpet+Chennai',
    imageKeyword: 'sowcarpet-food',
    photoUrl: 'https://images.pexels.com/photos/28926431/pexels-photo-28926431.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Sowcarpet+Food+Walk+Chennai',
  },
  {
    id: 'broken-bridge',
    name: 'Broken Bridge',
    category: 'photography',
    area: 'Adyar',
    lat: 13.0040,
    lng: 80.2710,
    rating: 4.3,
    reviewCount: 4200,
    budget: 'free',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'romantic', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '05:00', close: '19:00' },
      sunday: { open: '05:00', close: '19:00' },
    },
    description: 'Abandoned bridge over the Adyar estuary. Stunning sunset views and a photography hotspot.',
    insiderTip: 'Best at golden hour (5-6 PM). Wear shoes you don\'t mind getting muddy.',
    googleMapsUrl: 'https://maps.google.com/?q=Broken+Bridge+Adyar+Chennai',
    imageKeyword: 'broken-bridge-adyar',
    photoUrl: '/api/photo?q=Broken+Bridge+Chennai+Adyar',
    googleSearchUrl: 'https://www.google.com/search?q=Broken+Bridge+Chennai',
  },
  {
    id: 'mystery-rooms',
    name: 'Mystery Rooms',
    category: 'sports-fun',
    area: 'Nungambakkam',
    lat: 13.0580,
    lng: 80.2380,
    rating: 4.4,
    reviewCount: 3100,
    budget: 'under-2000',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: false,
    vibes: ['adventure', 'social'],
    groupTypes: ['friends', 'couple'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Escape room experiences with multiple themed rooms. Great for groups who love puzzles.',
    insiderTip: 'Book the "Haunted Asylum" room — it\'s the hardest but most fun. Go with 4+ people.',
    googleMapsUrl: 'https://maps.google.com/?q=Mystery+Rooms+Chennai',
    imageKeyword: 'mystery-rooms',
    photoUrl: 'https://images.pexels.com/photos/28471425/pexels-photo-28471425.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Mystery+Rooms+Chennai',
  },
  {
    id: 'dakshinachitra',
    name: 'Dakshinachitra',
    category: 'art-museums',
    area: 'OMR',
    lat: 12.8150,
    lng: 80.2470,
    rating: 4.3,
    reviewCount: 7800,
    budget: 'under-500',
    avgTimeMinutes: 150,
    indoor: true,
    outdoor: true,
    vibes: ['cultural', 'artsy', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '18:00' },
      sunday: { open: '10:00', close: '18:00' },
    },
    description: 'Living museum of South Indian art, architecture, and crafts on the ECR.',
    insiderTip: 'Don\'t miss the pottery workshop. The traditional houses from Kerala section is incredible.',
    googleMapsUrl: 'https://maps.google.com/?q=Dakshinachitra+Chennai',
    imageKeyword: 'dakshinachitra',
    photoUrl: '/api/photo?q=DakshinaChitra',
    googleSearchUrl: 'https://www.google.com/search?q=Dakshinachitra+Chennai',
  },
  {
    id: 'brew-room',
    name: 'The Brew Room',
    category: 'cafes',
    area: 'Mylapore',
    lat: 13.0340,
    lng: 80.2690,
    rating: 4.5,
    reviewCount: 3200,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: false,
    vibes: ['chill', 'social', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '08:00', close: '23:00' },
      sunday: { open: '08:00', close: '23:00' },
    },
    description: 'Specialty coffee haven in the heart of Mylapore. Great pour-overs and single origins.',
    insiderTip: 'Try the cold brew flight — 3 different beans. The upstairs seating is quieter.',
    googleMapsUrl: 'https://maps.google.com/?q=The+Brew+Room+Mylapore+Chennai',
    imageKeyword: 'brew-room-mylapore',
    photoUrl: 'https://images.pexels.com/photos/14823758/pexels-photo-14823758.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=The+Brew+Room+Chennai',
  },
  {
    id: 'chamiers-cafe',
    name: 'Chamiers Cafe',
    category: 'cafes',
    area: 'Adyar',
    lat: 13.0068,
    lng: 80.2530,
    rating: 4.4,
    reviewCount: 5800,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: true,
    vibes: ['chill', 'romantic', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:00', close: '22:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    description: 'Charming cafe in a colonial-era bungalow. Great pastries, bookshop upstairs.',
    insiderTip: 'The garden courtyard is magical in the evening. Pair a croissant with their house blend.',
    googleMapsUrl: 'https://maps.google.com/?q=Chamiers+Cafe+Chennai',
    imageKeyword: 'chamiers-cafe',
    photoUrl: 'https://images.pexels.com/photos/30403595/pexels-photo-30403595.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Chamiers+Cafe+Chennai',
  },
  {
    id: 'ciclo-cafe',
    name: 'Ciclo Cafe',
    category: 'cafes',
    area: 'Adyar',
    lat: 13.0110,
    lng: 80.2490,
    rating: 4.3,
    reviewCount: 4100,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: true,
    vibes: ['social', 'artsy', 'chill'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '08:00', close: '23:00' },
      sunday: { open: '08:00', close: '23:00' },
    },
    description: 'Cycling-themed cafe with a hip vibe. Great coffee, board games, and weekend events.',
    insiderTip: 'They host open mic nights on some Saturdays. Ask about the cycling meetups.',
    googleMapsUrl: 'https://maps.google.com/?q=Ciclo+Cafe+Chennai',
    imageKeyword: 'ciclo-cafe',
    photoUrl: 'https://images.pexels.com/photos/29976667/pexels-photo-29976667.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Ciclo+Cafe+Chennai',
  },
  {
    id: 'sandys-chocolate',
    name: 'Sandy\'s Chocolate Laboratory',
    category: 'cafes',
    area: 'Adyar',
    lat: 13.0058,
    lng: 80.2546,
    rating: 4.4,
    reviewCount: 6500,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['foodie', 'social', 'romantic'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '10:00', close: '23:00' },
    },
    description: 'Chocolate lover\'s paradise. Handcrafted desserts, shakes, and the famous death-by-chocolate.',
    insiderTip: 'The chocolate truffle cake is life-changing. Go after dinner as a dessert stop.',
    googleMapsUrl: 'https://maps.google.com/?q=Sandys+Chocolate+Laboratory+Chennai',
    imageKeyword: 'sandys-chocolate',
    photoUrl: 'https://images.pexels.com/photos/2223247/pexels-photo-2223247.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Sandy\+Chennai',
  },
  {
    id: 'writers-cafe',
    name: 'Writer\'s Cafe',
    category: 'cafes',
    area: 'T. Nagar',
    lat: 13.0410,
    lng: 80.2280,
    rating: 4.2,
    reviewCount: 2800,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: false,
    vibes: ['chill', 'artsy'],
    groupTypes: ['solo', 'couple'],
    openHours: {
      saturday: { open: '09:00', close: '22:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    description: 'Cozy book-themed cafe. Walls lined with books, perfect for a quiet afternoon.',
    insiderTip: 'Grab the window seat with the reading lamp. Their filter coffee is surprisingly great.',
    googleMapsUrl: 'https://maps.google.com/?q=Writers+Cafe+T+Nagar+Chennai',
    imageKeyword: 'writers-cafe',
    photoUrl: 'https://images.pexels.com/photos/29784882/pexels-photo-29784882.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Writer\+Chennai',
  },
  {
    id: 'cafe-de-paris',
    name: 'Cafe De Paris',
    category: 'cafes',
    area: 'Nungambakkam',
    lat: 13.0550,
    lng: 80.2400,
    rating: 4.1,
    reviewCount: 2200,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['chill', 'romantic'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:00', close: '22:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    description: 'French-inspired bistro cafe with great crepes, quiches, and European coffee.',
    insiderTip: 'The crepe suzette is a must. Quiet on Sunday mornings — perfect for a date.',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+De+Paris+Nungambakkam+Chennai',
    imageKeyword: 'cafe-de-paris',
    photoUrl: 'https://images.pexels.com/photos/35134952/pexels-photo-35134952.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Cafe+De+Paris+Chennai',
  },
  {
    id: 'tea-villa-cafe',
    name: 'Tea Villa Cafe',
    category: 'cafes',
    area: 'T. Nagar',
    lat: 13.0395,
    lng: 80.2310,
    rating: 4.2,
    reviewCount: 3400,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'chill', 'foodie'],
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '10:00', close: '23:00' },
    },
    description: 'Tea-focused cafe with 100+ varieties. Great snacks and a vibrant weekend crowd.',
    insiderTip: 'Try the Kashmiri Kahwa or the bubble tea. The loaded nachos are unreal.',
    googleMapsUrl: 'https://maps.google.com/?q=Tea+Villa+Cafe+T+Nagar+Chennai',
    imageKeyword: 'tea-villa-cafe',
    photoUrl: 'https://images.pexels.com/photos/702251/pexels-photo-702251.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Tea+Villa+Cafe+Chennai',
  },
  {
    id: 'kovalam-beach',
    name: 'Kovalam Beach',
    category: 'beaches',
    area: 'OMR',
    lat: 12.7904,
    lng: 80.2511,
    rating: 4.4,
    reviewCount: 7200,
    budget: 'free',
    avgTimeMinutes: 180,
    indoor: false,
    outdoor: true,
    vibes: ['adventure', 'nature', 'romantic'],
    groupTypes: ['couple', 'friends'],
    openHours: {
      saturday: { open: '05:00', close: '20:00' },
      sunday: { open: '05:00', close: '20:00' },
    },
    description: 'Pristine beach on ECR, less crowded than city beaches. Great for surfing and swimming.',
    insiderTip: 'Go early morning for the cleanest water. The nearby shacks serve fresh fish fry.',
    googleMapsUrl: 'https://maps.google.com/?q=Kovalam+Beach+Chennai',
    imageKeyword: 'kovalam-beach',
    photoUrl: '/api/photo?q=Kovalam+Beach+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Kovalam+Beach+Chennai',
  },
  {
    id: 'guindy-national-park',
    name: 'Guindy National Park',
    category: 'parks',
    area: 'Guindy',
    lat: 13.0040,
    lng: 80.2310,
    rating: 4.2,
    reviewCount: 8500,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'adventure', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '09:00', close: '17:30' },
      sunday: { open: '09:00', close: '17:30' },
    },
    description: 'One of the smallest national parks in India, right in the city. Deer, snakes, and birds.',
    insiderTip: 'Visit the Children\'s Park section if with kids. Spot blackbucks near the lake area.',
    googleMapsUrl: 'https://maps.google.com/?q=Guindy+National+Park+Chennai',
    imageKeyword: 'guindy-national-park',
    photoUrl: '/api/photo?q=Guindy+National+Park',
    googleSearchUrl: 'https://www.google.com/search?q=Guindy+National+Park+Chennai',
  },
  {
    id: 'express-avenue',
    name: 'Express Avenue',
    category: 'shopping',
    area: 'Egmore',
    lat: 13.0580,
    lng: 80.2680,
    rating: 4.4,
    reviewCount: 28000,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Premium mall in the heart of Chennai. Movies, food court, bowling, and great brands.',
    insiderTip: 'Hit the food court on level 3 for variety. The PVR Gold screen is worth the splurge.',
    googleMapsUrl: 'https://maps.google.com/?q=Express+Avenue+Mall+Chennai',
    imageKeyword: 'express-avenue',
    photoUrl: '/api/photo?q=Express+Avenue+Mall+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Express+Avenue+Chennai',
  },
  {
    id: 'mylapore-street-food',
    name: 'Mylapore Temple Street Food',
    category: 'street-food',
    area: 'Mylapore',
    lat: 13.0350,
    lng: 80.2700,
    rating: 4.3,
    reviewCount: 4800,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['foodie', 'cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '07:00', close: '22:00' },
      sunday: { open: '07:00', close: '22:00' },
    },
    description: 'Street food heaven around Kapaleeshwarar Temple. Dosas, bajjis, sundal, and sweets.',
    insiderTip: 'The evening bajji-bonda stalls near the temple tank are legendary. Try the rose milk.',
    googleMapsUrl: 'https://maps.google.com/?q=Mylapore+Temple+Street+Food+Chennai',
    imageKeyword: 'mylapore-street-food',
    photoUrl: '/api/photo?q=Mylapore+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Mylapore+Temple+Street+Food+Chennai',
  },
  {
    id: 'illusions-the-madras-pub',
    name: 'Illusions - The Madras Pub',
    category: 'cafes',
    area: 'Velachery',
    lat: 12.9790,
    lng: 80.2200,
    rating: 4.2,
    reviewCount: 3900,
    budget: 'under-2000',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'chill', 'foodie'],
    groupTypes: ['friends', 'couple'],
    openHours: {
      saturday: { open: '12:00', close: '23:30' },
      sunday: { open: '12:00', close: '23:30' },
    },
    description: 'Lively pub with great cocktails, live music on weekends, and solid bar food.',
    insiderTip: 'Go on Saturday night for the live band. The chicken wings and nachos are elite.',
    googleMapsUrl: 'https://maps.google.com/?q=Illusions+The+Madras+Pub+Chennai',
    imageKeyword: 'illusions-pub',
    photoUrl: 'https://images.pexels.com/photos/2209519/pexels-photo-2209519.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Illusions+-+The+Madras+Pub+Chennai',
  },
  {
    id: 'the-flying-elephant',
    name: 'The Flying Elephant',
    category: 'cafes',
    area: 'Guindy',
    lat: 13.0100,
    lng: 80.2230,
    rating: 4.3,
    reviewCount: 4500,
    budget: 'under-2000',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['foodie', 'social', 'romantic'],
    groupTypes: ['couple', 'friends'],
    openHours: {
      saturday: { open: '12:00', close: '23:00' },
      sunday: { open: '12:00', close: '23:00' },
    },
    description: 'Multi-level restaurant at Park Hyatt. Asian, European, and Indian live kitchens under one roof.',
    insiderTip: 'The Sunday brunch is legendary. Book in advance — it fills up fast. Try the sushi counter.',
    googleMapsUrl: 'https://maps.google.com/?q=The+Flying+Elephant+Park+Hyatt+Chennai',
    imageKeyword: 'flying-elephant',
    photoUrl: '/api/photo?q=ITC+Grand+Chola+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=The+Flying+Elephant+Chennai',
  },
  {
    id: 'bay-146',
    name: 'Bay 146',
    category: 'cafes',
    area: 'Besant Nagar',
    lat: 13.0005,
    lng: 80.2700,
    rating: 4.1,
    reviewCount: 2600,
    budget: 'under-500',
    avgTimeMinutes: 75,
    indoor: true,
    outdoor: true,
    vibes: ['chill', 'romantic', 'social'],
    groupTypes: ['couple', 'friends'],
    openHours: {
      saturday: { open: '11:00', close: '23:00' },
      sunday: { open: '11:00', close: '23:00' },
    },
    description: 'Beachside cafe near Elliot\'s Beach. Chill vibes, sea breeze, and good comfort food.',
    insiderTip: 'Grab the outdoor table at sunset. Their milkshakes are the real deal.',
    googleMapsUrl: 'https://maps.google.com/?q=Bay+146+Besant+Nagar+Chennai',
    imageKeyword: 'bay-146',
    photoUrl: 'https://images.pexels.com/photos/6126940/pexels-photo-6126940.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Bay+146+Chennai',
  },
  {
    id: 'murugan-idli-shop',
    name: 'Murugan Idli Shop',
    category: 'street-food',
    area: 'T. Nagar',
    lat: 13.0425,
    lng: 80.2345,
    rating: 4.6,
    reviewCount: 22000,
    budget: 'under-500',
    avgTimeMinutes: 45,
    indoor: true,
    outdoor: false,
    vibes: ['foodie', 'cultural', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '22:30' },
      sunday: { open: '06:00', close: '22:30' },
    },
    description: 'Legendary idli chain. Fluffy idlis, crispy dosas, and the iconic ghee podi combo.',
    insiderTip: 'The ghee podi idli is non-negotiable. Go before 8 AM to avoid the queue.',
    googleMapsUrl: 'https://maps.google.com/?q=Murugan+Idli+Shop+T+Nagar+Chennai',
    imageKeyword: 'murugan-idli',
    photoUrl: '/api/photo?q=Murugan+Idli+Shop',
    googleSearchUrl: 'https://www.google.com/search?q=Murugan+Idli+Shop+Chennai',
  },
  {
    id: 'junior-kuppanna',
    name: 'Junior Kuppanna',
    category: 'street-food',
    area: 'Egmore',
    lat: 13.0720,
    lng: 80.2600,
    rating: 4.4,
    reviewCount: 15000,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['foodie', 'social'],
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '11:30', close: '23:00' },
      sunday: { open: '11:30', close: '23:00' },
    },
    description: 'Chettinad cuisine at its finest. Fiery curries, biryani, and the famous mud pot chicken.',
    insiderTip: 'The Nandu (crab) Rasam is a must-try. Go for lunch — dinner queues are brutal.',
    googleMapsUrl: 'https://maps.google.com/?q=Junior+Kuppanna+Egmore+Chennai',
    imageKeyword: 'junior-kuppanna',
    photoUrl: 'https://images.pexels.com/photos/3531700/pexels-photo-3531700.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Junior+Kuppanna+Chennai',
  },
  {
    id: 'marina-food-stalls',
    name: 'Marina Beach Food Stalls',
    category: 'street-food',
    area: 'Mylapore',
    lat: 13.0490,
    lng: 80.2810,
    rating: 4.0,
    reviewCount: 8900,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['foodie', 'social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '16:00', close: '22:00' },
      sunday: { open: '16:00', close: '22:00' },
    },
    description: 'Iconic beach-side street food. Corn, sundal, bajji, murukku, ice cream — the full Chennai experience.',
    insiderTip: 'The rose milk and badam milk vendors near the lighthouse end are the best.',
    googleMapsUrl: 'https://maps.google.com/?q=Marina+Beach+Food+Stalls+Chennai',
    imageKeyword: 'marina-food-stalls',
    photoUrl: '/api/photo?q=Marina+Beach+Chennai+food',
    googleSearchUrl: 'https://www.google.com/search?q=Marina+Beach+Food+Stalls+Chennai',
  },
  {
    id: 'besant-nagar-food-street',
    name: 'Besant Nagar Food Street',
    category: 'street-food',
    area: 'Besant Nagar',
    lat: 13.0010,
    lng: 80.2690,
    rating: 4.2,
    reviewCount: 5200,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['foodie', 'social'],
    groupTypes: ['couple', 'friends'],
    openHours: {
      saturday: { open: '16:00', close: '23:00' },
      sunday: { open: '16:00', close: '23:00' },
    },
    description: 'Food stalls and small eateries along the beach road. Shawarma, momos, and ice cream galore.',
    insiderTip: 'The shawarma near the 2nd cross signal is the OG. Pair it with a thick shake from next door.',
    googleMapsUrl: 'https://maps.google.com/?q=Besant+Nagar+Food+Street+Chennai',
    imageKeyword: 'besant-nagar-food',
    photoUrl: '/api/photo?q=Besant+Nagar+Beach+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Besant+Nagar+Food+Street+Chennai',
  },
  {
    id: 'thalapakattu-biryani',
    name: 'Dindigul Thalappakatti Biryani',
    category: 'street-food',
    area: 'T. Nagar',
    lat: 13.0430,
    lng: 80.2350,
    rating: 4.3,
    reviewCount: 18000,
    budget: 'under-500',
    avgTimeMinutes: 45,
    indoor: true,
    outdoor: false,
    vibes: ['foodie'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '11:00', close: '23:00' },
      sunday: { open: '11:00', close: '23:00' },
    },
    description: 'Legendary Dindigul-style biryani. Seeraga samba rice, tender meat, and explosive flavour.',
    insiderTip: 'Order the mutton biryani with a side of brinjal curry. Skip the starters — go straight for biryani.',
    googleMapsUrl: 'https://maps.google.com/?q=Thalappakatti+Biryani+T+Nagar+Chennai',
    imageKeyword: 'thalappakatti-biryani',
    photoUrl: '/api/photo?q=Dindigul+Thalappakatti',
    googleSearchUrl: 'https://www.google.com/search?q=Dindigul+Thalappakatti+Biryani+Chennai',
  },
  {
    id: 'fort-st-george',
    name: 'Fort St. George',
    category: 'temples-heritage',
    area: 'Egmore',
    lat: 13.0800,
    lng: 80.2878,
    rating: 4.2,
    reviewCount: 9500,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['cultural', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '09:00', close: '17:00' },
      sunday: { open: '09:00', close: '17:00' },
    },
    description: 'First English fortress in India (1644). Fort museum, St. Mary\'s Church, and colonial history.',
    insiderTip: 'The fort museum has original letters from Clive and Cornwallis. Photography is free inside.',
    googleMapsUrl: 'https://maps.google.com/?q=Fort+St+George+Chennai',
    imageKeyword: 'fort-st-george',
    photoUrl: '/api/photo?q=Fort+St+George+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Fort+St.+George+Chennai',
  },
  {
    id: 'san-thome-cathedral',
    name: 'San Thome Cathedral',
    category: 'temples-heritage',
    area: 'Mylapore',
    lat: 13.0326,
    lng: 80.2778,
    rating: 4.5,
    reviewCount: 11000,
    budget: 'free',
    avgTimeMinutes: 45,
    indoor: true,
    outdoor: true,
    vibes: ['cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '20:00' },
      sunday: { open: '06:00', close: '20:00' },
    },
    description: 'Gothic cathedral built over the tomb of St. Thomas the Apostle. Stunning architecture.',
    insiderTip: 'The underground tomb chapel is hauntingly beautiful. Visit at sunset for the best light.',
    googleMapsUrl: 'https://maps.google.com/?q=San+Thome+Cathedral+Chennai',
    imageKeyword: 'san-thome-cathedral',
    photoUrl: '/api/photo?q=San+Thome+Cathedral',
    googleSearchUrl: 'https://www.google.com/search?q=San+Thome+Cathedral+Chennai',
  },
  {
    id: 'government-museum',
    name: 'Government Museum Egmore',
    category: 'art-museums',
    area: 'Egmore',
    lat: 13.0694,
    lng: 80.2570,
    rating: 4.1,
    reviewCount: 7200,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['cultural', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '09:30', close: '17:00' },
      sunday: { open: '09:30', close: '17:00' },
    },
    description: 'Second oldest museum in India. Bronze gallery, archaeology, and natural history wings.',
    insiderTip: 'The Chola bronze gallery is world-class — don\'t skip it. Allow 2 hours minimum.',
    googleMapsUrl: 'https://maps.google.com/?q=Government+Museum+Egmore+Chennai',
    imageKeyword: 'government-museum-egmore',
    photoUrl: '/api/photo?q=Government+Museum+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Government+Museum+Egmore+Chennai',
  },
  {
    id: 'vr-chennai',
    name: 'VR Chennai',
    category: 'shopping',
    area: 'Anna Nagar',
    lat: 13.0920,
    lng: 80.2120,
    rating: 4.5,
    reviewCount: 25000,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    description: 'Premium mall in Anna Nagar. Great food court, IMAX, high-end stores, and rooftop dining.',
    insiderTip: 'The IMAX screen here is the best in Chennai. The rooftop restaurants have great views.',
    googleMapsUrl: 'https://maps.google.com/?q=VR+Chennai+Anna+Nagar',
    imageKeyword: 'vr-chennai',
    photoUrl: 'https://images.pexels.com/photos/14230221/pexels-photo-14230221.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=VR+Chennai+Chennai',
  },
  {
    id: 't-nagar-ranganathan',
    name: 'T. Nagar Ranganathan Street',
    category: 'shopping',
    area: 'T. Nagar',
    lat: 13.0400,
    lng: 80.2340,
    rating: 4.2,
    reviewCount: 15000,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: false,
    outdoor: true,
    vibes: ['social', 'cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '09:00', close: '21:30' },
      sunday: { open: '09:00', close: '21:30' },
    },
    description: 'Chennai\'s busiest shopping street. Sarees, jewellery, textiles, and street shopping galore.',
    insiderTip: 'Go early morning (before 10 AM) to avoid the insane crowds. Bargain hard at street stalls.',
    googleMapsUrl: 'https://maps.google.com/?q=Ranganathan+Street+T+Nagar+Chennai',
    imageKeyword: 'ranganathan-street',
    photoUrl: '/api/photo?q=Ranganathan+Street+T+Nagar',
    googleSearchUrl: 'https://www.google.com/search?q=T.+Nagar+Ranganathan+Street+Chennai',
  },
  {
    id: 'cholamandal-artists',
    name: 'Cholamandal Artists\' Village',
    category: 'art-museums',
    area: 'Thiruvanmiyur',
    lat: 12.9540,
    lng: 80.2540,
    rating: 4.3,
    reviewCount: 3200,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: true,
    vibes: ['artsy', 'cultural'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '09:30', close: '18:00' },
      sunday: { open: '09:30', close: '18:00' },
    },
    description: 'India\'s largest self-supporting artists\' commune. Galleries, sculptures, and live art.',
    insiderTip: 'Talk to the resident artists — many are happy to show their studios. Buy art directly.',
    googleMapsUrl: 'https://maps.google.com/?q=Cholamandal+Artists+Village+Chennai',
    imageKeyword: 'cholamandal-village',
    photoUrl: '/api/photo?q=Cholamandal+Artists+Village',
    googleSearchUrl: 'https://www.google.com/search?q=Cholamandal+Artists\+Chennai',
  },
  {
    id: 'birla-planetarium',
    name: 'Birla Planetarium',
    category: 'art-museums',
    area: 'Guindy',
    lat: 13.0130,
    lng: 80.2340,
    rating: 4.1,
    reviewCount: 6800,
    budget: 'under-500',
    avgTimeMinutes: 60,
    indoor: true,
    outdoor: false,
    vibes: ['family', 'cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '17:30' },
      sunday: { open: '10:00', close: '17:30' },
    },
    description: 'Dome-shaped planetarium with sky shows. Great for kids and space enthusiasts.',
    insiderTip: 'Catch the 3:30 PM English show — it\'s the best one. Combine with Guindy Park next door.',
    googleMapsUrl: 'https://maps.google.com/?q=Birla+Planetarium+Chennai',
    imageKeyword: 'birla-planetarium',
    photoUrl: '/api/photo?q=Birla+Planetarium+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Birla+Planetarium+Chennai',
  },
  {
    id: 'covelong-surf',
    name: 'Covelong Point Surf School',
    category: 'sports-fun',
    area: 'OMR',
    lat: 12.7830,
    lng: 80.2560,
    rating: 4.5,
    reviewCount: 2800,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: false,
    outdoor: true,
    vibes: ['adventure', 'nature'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '06:00', close: '18:00' },
      sunday: { open: '06:00', close: '18:00' },
    },
    description: 'Learn surfing on the ECR! Beginner-friendly waves, board rental, and certified instructors.',
    insiderTip: 'Book the 7 AM slot for the best waves and fewer people. They provide everything.',
    googleMapsUrl: 'https://maps.google.com/?q=Covelong+Point+Surf+School+Chennai',
    imageKeyword: 'covelong-surf',
    photoUrl: '/api/photo?q=Covelong+Beach+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Covelong+Point+Surf+School+Chennai',
  },
  {
    id: 'dugout-trampoline',
    name: 'Dugout Trampoline Park',
    category: 'sports-fun',
    area: 'OMR',
    lat: 12.9350,
    lng: 80.2290,
    rating: 4.3,
    reviewCount: 4200,
    budget: 'under-2000',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['adventure', 'social', 'family'],
    groupTypes: ['friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '10:00', close: '21:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    description: 'Massive trampoline park with foam pits, dodgeball courts, and ninja obstacle courses.',
    insiderTip: 'Wear grip socks (they sell them there). Book the 2-hour package — 1 hour flies by.',
    googleMapsUrl: 'https://maps.google.com/?q=Dugout+Trampoline+Park+OMR+Chennai',
    imageKeyword: 'dugout-trampoline',
    photoUrl: 'https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Dugout+Trampoline+Park+Chennai',
  },
  {
    id: 'ashtalakshmi-temple',
    name: 'Ashtalakshmi Temple',
    category: 'temples-heritage',
    area: 'Besant Nagar',
    lat: 13.0005,
    lng: 80.2720,
    rating: 4.4,
    reviewCount: 8700,
    budget: 'free',
    avgTimeMinutes: 45,
    indoor: false,
    outdoor: true,
    vibes: ['cultural', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:30', close: '12:00' },
      sunday: { open: '06:30', close: '12:00' },
    },
    description: 'Beautiful seaside temple dedicated to eight forms of Lakshmi. Stunning ocean views.',
    insiderTip: 'Visit at sunrise for an unforgettable experience. Combine with Elliot\'s Beach walk after.',
    googleMapsUrl: 'https://maps.google.com/?q=Ashtalakshmi+Temple+Chennai',
    imageKeyword: 'ashtalakshmi-temple',
    photoUrl: '/api/photo?q=Ashtalakshmi+Temple+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Ashtalakshmi+Temple+Chennai',
  },
  {
    id: 'marundeeswarar-temple',
    name: 'Marundeeswarar Temple',
    category: 'temples-heritage',
    area: 'Thiruvanmiyur',
    lat: 12.9842,
    lng: 80.2597,
    rating: 4.6,
    reviewCount: 6500,
    budget: 'free',
    avgTimeMinutes: 45,
    indoor: false,
    outdoor: true,
    vibes: ['cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '05:30', close: '12:30' },
      sunday: { open: '05:30', close: '12:30' },
    },
    description: 'Ancient Shiva temple known as the "temple of healing." Beautiful Dravidian architecture.',
    insiderTip: 'The temple tank area is peaceful. Visit early morning for the best darshan without crowds.',
    googleMapsUrl: 'https://maps.google.com/?q=Marundeeswarar+Temple+Thiruvanmiyur+Chennai',
    imageKeyword: 'marundeeswarar-temple',
    photoUrl: '/api/photo?q=Marundeeswarar+Temple',
    googleSearchUrl: 'https://www.google.com/search?q=Marundeeswarar+Temple+Chennai',
  },
  {
    id: 'thiruvalluvar-beach',
    name: 'Thiruvalluvar Nagar Beach',
    category: 'beaches',
    area: 'Thiruvanmiyur',
    lat: 12.9870,
    lng: 80.2680,
    rating: 4.0,
    reviewCount: 2100,
    budget: 'free',
    avgTimeMinutes: 60,
    indoor: false,
    outdoor: true,
    vibes: ['chill', 'nature'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '05:00', close: '21:00' },
      sunday: { open: '05:00', close: '21:00' },
    },
    description: 'Quieter alternative to Besant Nagar beach. Locals\' secret for peaceful evening walks.',
    insiderTip: 'Much less crowded than Elliot\'s. Best on weekday evenings but still calm on weekends.',
    googleMapsUrl: 'https://maps.google.com/?q=Thiruvalluvar+Nagar+Beach+Chennai',
    imageKeyword: 'thiruvalluvar-beach',
    photoUrl: 'https://images.pexels.com/photos/35919338/pexels-photo-35919338.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Thiruvalluvar+Nagar+Beach+Chennai',
  },
  {
    id: 'triplicane-biryani',
    name: 'Triplicane Biryani Street',
    category: 'street-food',
    area: 'Egmore',
    lat: 13.0570,
    lng: 80.2760,
    rating: 4.4,
    reviewCount: 6800,
    budget: 'under-500',
    avgTimeMinutes: 45,
    indoor: true,
    outdoor: true,
    vibes: ['foodie'],
    groupTypes: ['solo', 'friends'],
    openHours: {
      saturday: { open: '11:00', close: '23:00' },
      sunday: { open: '11:00', close: '23:00' },
    },
    description: 'Old Madras biryani hub. Multiple legendary joints serving Chennai\'s finest biryani since decades.',
    insiderTip: 'Star Biryani and Pakoda Corner are the local favourites. Go for lunch — sells out by 2 PM.',
    googleMapsUrl: 'https://maps.google.com/?q=Triplicane+Biryani+Chennai',
    imageKeyword: 'triplicane-biryani',
    photoUrl: '/api/photo?q=Triplicane+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Triplicane+Biryani+Street+Chennai',
  },

  // ===== NIGHTLIFE & PUBS =====
  {
    id: '10-downing-street',
    name: '10 Downing Street',
    category: 'nightlife',
    area: 'Nungambakkam',
    lat: 13.0560,
    lng: 80.2410,
    rating: 4.2,
    reviewCount: 5400,
    budget: 'under-2000',
    avgTimeMinutes: 150,
    indoor: true,
    outdoor: false,
    vibes: ['nightout', 'social'],
    groupTypes: ['friends', 'couple'],
    openHours: {
      saturday: { open: '17:00', close: '23:30' },
      sunday: { open: '17:00', close: '23:30' },
    },
    description: 'Popular pub with great cocktails, DJ nights, and a lively Saturday crowd.',
    insiderTip: 'Saturday night is packed — reach by 8 PM to get a good table. Try the LIIT.',
    googleMapsUrl: 'https://maps.google.com/?q=10+Downing+Street+Nungambakkam+Chennai',
    imageKeyword: '10-downing-street',
    photoUrl: 'https://images.pexels.com/photos/234547/pexels-photo-234547.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=10+Downing+Street+Chennai',
  },
  {
    id: 'the-vault',
    name: 'The Vault',
    category: 'nightlife',
    area: 'Nungambakkam',
    lat: 13.0555,
    lng: 80.2390,
    rating: 4.1,
    reviewCount: 3200,
    budget: 'under-2000',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['nightout', 'social', 'chill'],
    groupTypes: ['friends', 'couple'],
    openHours: {
      saturday: { open: '18:00', close: '23:30' },
      sunday: { open: '18:00', close: '23:30' },
    },
    description: 'Speakeasy-style bar with craft cocktails and dim lighting. Great for a chill night out.',
    insiderTip: 'Ask for the off-menu Old Fashioned. The cheese platter is solid.',
    googleMapsUrl: 'https://maps.google.com/?q=The+Vault+Bar+Nungambakkam+Chennai',
    imageKeyword: 'the-vault-bar',
    photoUrl: 'https://images.pexels.com/photos/6126940/pexels-photo-6126940.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=The+Vault+Chennai',
  },
  {
    id: 'leather-bar',
    name: 'The Leather Bar',
    category: 'nightlife',
    area: 'Egmore',
    lat: 13.0620,
    lng: 80.2650,
    rating: 4.3,
    reviewCount: 4100,
    budget: 'under-2000',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['nightout', 'romantic', 'chill'],
    groupTypes: ['couple', 'friends'],
    openHours: {
      saturday: { open: '17:00', close: '23:30' },
      sunday: { open: '17:00', close: '23:30' },
    },
    description: 'Classy bar at The Park Hotel. Live music some nights, great whiskey selection.',
    insiderTip: 'Friday/Saturday have live jazz. Dress smart — no shorts or flip-flops.',
    googleMapsUrl: 'https://maps.google.com/?q=The+Leather+Bar+Park+Hotel+Chennai',
    imageKeyword: 'leather-bar',
    photoUrl: 'https://images.pexels.com/photos/2209519/pexels-photo-2209519.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=The+Leather+Bar+Chennai',
  },

  // ===== WELLNESS & SPA =====
  {
    id: 'o2-spa-velachery',
    name: 'O2 Spa',
    category: 'wellness',
    area: 'Velachery',
    lat: 12.9900,
    lng: 80.2185,
    rating: 4.2,
    reviewCount: 2800,
    budget: 'under-2000',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: false,
    vibes: ['wellness', 'chill'],
    groupTypes: ['solo', 'couple'],
    openHours: {
      saturday: { open: '09:00', close: '21:00' },
      sunday: { open: '09:00', close: '21:00' },
    },
    description: 'Relaxing spa inside Phoenix MarketCity. Thai, Swedish, and Ayurvedic massages.',
    insiderTip: 'Book the 90-min Balinese massage. Weekend slots fill fast — book a day ahead.',
    googleMapsUrl: 'https://maps.google.com/?q=O2+Spa+Phoenix+Mall+Chennai',
    imageKeyword: 'o2-spa',
    photoUrl: 'https://images.pexels.com/photos/3865570/pexels-photo-3865570.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=O2+Spa+Chennai',
  },
  {
    id: 'mudra-yoga',
    name: 'Mudra Yoga Shala',
    category: 'wellness',
    area: 'Mylapore',
    lat: 13.0350,
    lng: 80.2660,
    rating: 4.5,
    reviewCount: 1200,
    budget: 'under-500',
    avgTimeMinutes: 90,
    indoor: true,
    outdoor: false,
    vibes: ['wellness', 'chill', 'nature'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '06:00', close: '19:00' },
      sunday: { open: '06:00', close: '19:00' },
    },
    description: 'Traditional yoga studio offering drop-in weekend classes. Hatha, Vinyasa, and meditation.',
    insiderTip: 'The 7 AM Saturday Vinyasa class is transformative. Bring your own mat for comfort.',
    googleMapsUrl: 'https://maps.google.com/?q=Yoga+Studio+Mylapore+Chennai',
    imageKeyword: 'yoga-mylapore',
    photoUrl: 'https://images.pexels.com/photos/3822169/pexels-photo-3822169.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Mudra+Yoga+Shala+Chennai',
  },
  {
    id: 'spafusion',
    name: 'Spa Fusion',
    category: 'wellness',
    area: 'Anna Nagar',
    lat: 13.0870,
    lng: 80.2110,
    rating: 4.3,
    reviewCount: 1800,
    budget: 'under-2000',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['wellness', 'chill', 'romantic'],
    groupTypes: ['solo', 'couple'],
    openHours: {
      saturday: { open: '10:00', close: '21:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    description: 'Premium spa near VR Mall. Couple packages, aromatherapy, and deep tissue specials.',
    insiderTip: 'The couple spa package on weekends is great value. Book the 2 PM slot for fewer people.',
    googleMapsUrl: 'https://maps.google.com/?q=Spa+Anna+Nagar+Chennai',
    imageKeyword: 'spa-anna-nagar',
    photoUrl: 'https://images.pexels.com/photos/7700/pexels-photo-7700.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Spa+Fusion+Chennai',
  },

  // ===== COWORKING & STUDY SPOTS =====
  {
    id: 'ikigai-cowork',
    name: 'Ikigai Coworking',
    category: 'coworking-study',
    area: 'Nungambakkam',
    lat: 13.0575,
    lng: 80.2420,
    rating: 4.4,
    reviewCount: 900,
    budget: 'under-500',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['productive', 'social', 'chill'],
    groupTypes: ['solo', 'friends'],
    openHours: {
      saturday: { open: '08:00', close: '22:00' },
      sunday: { open: '08:00', close: '22:00' },
    },
    description: 'Modern coworking space with day passes. High-speed WiFi, coffee, and quiet zones.',
    insiderTip: 'Day pass is ₹350. The quiet zone upstairs is perfect for deep work. Free coffee all day.',
    googleMapsUrl: 'https://maps.google.com/?q=Ikigai+Coworking+Chennai',
    imageKeyword: 'ikigai-cowork',
    photoUrl: 'https://images.pexels.com/photos/3831879/pexels-photo-3831879.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Ikigai+Coworking+Chennai',
  },
  {
    id: 'connemara-library',
    name: 'Connemara Public Library',
    category: 'coworking-study',
    area: 'Egmore',
    lat: 13.0700,
    lng: 80.2580,
    rating: 4.3,
    reviewCount: 3500,
    budget: 'free',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['productive', 'chill', 'cultural'],
    groupTypes: ['solo'],
    openHours: {
      saturday: { open: '09:30', close: '18:00' },
      sunday: { open: '09:30', close: '18:00' },
    },
    description: 'Historic public library (1890). Beautiful Indo-Saracenic architecture. Free reading room.',
    insiderTip: 'The reading room is air-conditioned and silent. Carry your own laptop charger.',
    googleMapsUrl: 'https://maps.google.com/?q=Connemara+Public+Library+Chennai',
    imageKeyword: 'connemara-library',
    photoUrl: '/api/photo?q=Connemara+Public+Library',
    googleSearchUrl: 'https://www.google.com/search?q=Connemara+Public+Library+Chennai',
  },
  {
    id: 'starbucks-ecr',
    name: 'Starbucks ECR (Study Spot)',
    category: 'coworking-study',
    area: 'Besant Nagar',
    lat: 13.0010,
    lng: 80.2650,
    rating: 4.0,
    reviewCount: 2200,
    budget: 'under-500',
    avgTimeMinutes: 150,
    indoor: true,
    outdoor: true,
    vibes: ['productive', 'chill', 'social'],
    groupTypes: ['solo', 'friends'],
    openHours: {
      saturday: { open: '07:00', close: '23:00' },
      sunday: { open: '07:00', close: '23:00' },
    },
    description: 'Popular study/work spot among students. Good WiFi, power outlets, and ocean breeze.',
    insiderTip: 'Grab the upstairs window seat — ocean view while you work. Go early on weekends.',
    googleMapsUrl: 'https://maps.google.com/?q=Starbucks+ECR+Chennai',
    imageKeyword: 'starbucks-ecr',
    photoUrl: 'https://images.pexels.com/photos/6779226/pexels-photo-6779226.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Starbucks+ECR+(Study+Spot)+Chennai',
  },

  // ===== MOVIES & ENTERTAINMENT =====
  {
    id: 'sathyam-cinemas',
    name: 'Sathyam Cinemas',
    category: 'movies-entertainment',
    area: 'Egmore',
    lat: 13.0600,
    lng: 80.2520,
    rating: 4.5,
    reviewCount: 35000,
    budget: 'under-500',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'chill', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '09:00', close: '23:30' },
      sunday: { open: '09:00', close: '23:30' },
    },
    description: 'Chennai\'s most iconic movie theatre. Great sound, Subliminal cafe, and the full movie experience.',
    insiderTip: 'Book Row H-K for the best view. The Subliminal cafe samosa and cold coffee is a ritual.',
    googleMapsUrl: 'https://maps.google.com/?q=Sathyam+Cinemas+Chennai',
    imageKeyword: 'sathyam-cinemas',
    photoUrl: '/api/photo?q=Sathyam+Cinemas+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=Sathyam+Cinemas+Chennai',
  },
  {
    id: 'pvr-vr-chennai',
    name: 'PVR IMAX - VR Chennai',
    category: 'movies-entertainment',
    area: 'Anna Nagar',
    lat: 13.0920,
    lng: 80.2125,
    rating: 4.4,
    reviewCount: 12000,
    budget: 'under-500',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'family'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '09:00', close: '23:30' },
      sunday: { open: '09:00', close: '23:30' },
    },
    description: 'Best IMAX screen in Chennai inside VR Mall. Premium recliners and Dolby Atmos.',
    insiderTip: 'The IMAX 3D screen is worth the ₹200 extra. Combine with dinner at the VR food court.',
    googleMapsUrl: 'https://maps.google.com/?q=PVR+IMAX+VR+Chennai',
    imageKeyword: 'pvr-imax-vr',
    photoUrl: '/api/photo?q=PVR+VR+Chennai',
    googleSearchUrl: 'https://www.google.com/search?q=PVR+IMAX+-+VR+Chennai+Chennai',
  },
  {
    id: 'smaaash',
    name: 'Smaaash Gaming Zone',
    category: 'movies-entertainment',
    area: 'Velachery',
    lat: 12.9930,
    lng: 80.2170,
    rating: 4.0,
    reviewCount: 4800,
    budget: 'under-2000',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: false,
    vibes: ['social', 'adventure', 'nightout'],
    groupTypes: ['friends', 'couple', 'large-group'],
    openHours: {
      saturday: { open: '11:00', close: '22:00' },
      sunday: { open: '11:00', close: '22:00' },
    },
    description: 'Gaming, bowling, VR, go-karting under one roof at Phoenix Mall. Perfect group outing.',
    insiderTip: 'The VR roller coaster is insane. Buy the combo pass — individual games cost more.',
    googleMapsUrl: 'https://maps.google.com/?q=Smaaash+Phoenix+Mall+Chennai',
    imageKeyword: 'smaaash-gaming',
    photoUrl: 'https://images.pexels.com/photos/28471425/pexels-photo-28471425.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Smaaash+Gaming+Zone+Chennai',
  },

  // ===== NATURE GETAWAYS (weekend drives) =====
  {
    id: 'muttukadu-boathouse',
    name: 'Muttukadu Boat House',
    category: 'nature-getaways',
    area: 'OMR',
    lat: 12.8150,
    lng: 80.2420,
    rating: 4.1,
    reviewCount: 9500,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'adventure', 'family'],
    groupTypes: ['couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '09:00', close: '17:30' },
      sunday: { open: '09:00', close: '17:30' },
    },
    description: 'TTDC boathouse on the backwaters. Pedal boats, speed boats, and kayaks on the ECR.',
    insiderTip: 'Go before 11 AM — the queue gets crazy by noon. Speed boat ride is worth the price.',
    googleMapsUrl: 'https://maps.google.com/?q=Muttukadu+Boat+House+Chennai',
    imageKeyword: 'muttukadu-boathouse',
    photoUrl: '/api/photo?q=Muttukadu+Boat+House',
    googleSearchUrl: 'https://www.google.com/search?q=Muttukadu+Boat+House+Chennai',
  },
  {
    id: 'vedanthangal-bird-sanctuary',
    name: 'Vedanthangal Bird Sanctuary',
    category: 'nature-getaways',
    area: 'Tambaram',
    lat: 12.5460,
    lng: 79.8580,
    rating: 4.2,
    reviewCount: 3800,
    budget: 'under-500',
    avgTimeMinutes: 180,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'chill'],
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '06:00', close: '18:00' },
      sunday: { open: '06:00', close: '18:00' },
    },
    description: 'One of India\'s oldest bird sanctuaries. 75km from Chennai. Thousands of migratory birds.',
    insiderTip: 'Best between Nov-Feb for migratory birds. Carry binoculars. Early morning is magical.',
    googleMapsUrl: 'https://maps.google.com/?q=Vedanthangal+Bird+Sanctuary',
    imageKeyword: 'vedanthangal-birds',
    photoUrl: '/api/photo?q=Vedanthangal+Bird+Sanctuary',
    googleSearchUrl: 'https://www.google.com/search?q=Vedanthangal+Bird+Sanctuary+Chennai',
  },
  {
    id: 'mahabalipuram',
    name: 'Mahabalipuram (Day Trip)',
    category: 'nature-getaways',
    area: 'OMR',
    lat: 12.6172,
    lng: 80.1927,
    rating: 4.6,
    reviewCount: 42000,
    budget: 'under-500',
    avgTimeMinutes: 300,
    indoor: false,
    outdoor: true,
    vibes: ['cultural', 'nature', 'adventure', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends', 'family', 'large-group'],
    openHours: {
      saturday: { open: '06:00', close: '18:00' },
      sunday: { open: '06:00', close: '18:00' },
    },
    description: 'UNESCO World Heritage Site. Ancient rock-cut temples, Shore Temple, and Five Rathas. 60km from Chennai.',
    insiderTip: 'Go early to beat tourist crowds. The Shore Temple at sunrise is breathtaking. Eat at one of the beach shacks.',
    googleMapsUrl: 'https://maps.google.com/?q=Mahabalipuram+Tamil+Nadu',
    imageKeyword: 'mahabalipuram',
    photoUrl: '/api/photo?q=Mahabalipuram+Shore+Temple',
    googleSearchUrl: 'https://www.google.com/search?q=Mahabalipuram+(Day+Trip)+Chennai',
  },
  {
    id: 'tholkappia-poonga',
    name: 'Tholkappia Poonga (Adyar Eco Park)',
    category: 'nature-getaways',
    area: 'Adyar',
    lat: 13.0040,
    lng: 80.2620,
    rating: 4.3,
    reviewCount: 5200,
    budget: 'free',
    avgTimeMinutes: 90,
    indoor: false,
    outdoor: true,
    vibes: ['nature', 'chill'],
    groupTypes: ['solo', 'couple', 'family'],
    openHours: {
      saturday: { open: '06:00', close: '18:00' },
      sunday: { open: '06:00', close: '18:00' },
    },
    description: 'Restored mangrove forest along the Adyar estuary. Walking trails, bird watching, and serenity.',
    insiderTip: 'The boardwalk through the mangroves is stunning. Carry mosquito repellent in the evening.',
    googleMapsUrl: 'https://maps.google.com/?q=Tholkappia+Poonga+Chennai',
    imageKeyword: 'tholkappia-poonga',
    photoUrl: '/api/photo?q=Tholkappia+Poonga+Adyar+Eco+Park',
    googleSearchUrl: 'https://www.google.com/search?q=Tholkappia+Poonga+(Adyar+Eco+Park)+Chennai',
  },

  // ===== WORKSHOPS & CLASSES =====
  {
    id: 'kalakshetra',
    name: 'Kalakshetra Foundation',
    category: 'workshops-classes',
    area: 'Thiruvanmiyur',
    lat: 12.9820,
    lng: 80.2580,
    rating: 4.5,
    reviewCount: 4800,
    budget: 'under-500',
    avgTimeMinutes: 120,
    indoor: true,
    outdoor: true,
    vibes: ['cultural', 'artsy', 'learning'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '08:30', close: '17:30' },
      sunday: { open: '08:30', close: '17:30' },
    },
    description: 'Legendary art academy. Weekend visitors can watch dance rehearsals, buy handloom, and tour the campus.',
    insiderTip: 'Check their website for weekend performances. The weaving centre sells beautiful handloom.',
    googleMapsUrl: 'https://maps.google.com/?q=Kalakshetra+Foundation+Chennai',
    imageKeyword: 'kalakshetra',
    photoUrl: '/api/photo?q=Kalakshetra+Foundation',
    googleSearchUrl: 'https://www.google.com/search?q=Kalakshetra+Foundation+Chennai',
  },
  {
    id: 'pottery-workshop-ecr',
    name: 'The Potter\'s Shed (Pottery Workshop)',
    category: 'workshops-classes',
    area: 'OMR',
    lat: 12.8900,
    lng: 80.2450,
    rating: 4.4,
    reviewCount: 1100,
    budget: 'under-2000',
    avgTimeMinutes: 150,
    indoor: true,
    outdoor: false,
    vibes: ['artsy', 'learning', 'chill'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '10:00', close: '18:00' },
      sunday: { open: '10:00', close: '18:00' },
    },
    description: 'Weekend pottery workshops on ECR. Learn wheel throwing, hand-building, and take your piece home.',
    insiderTip: 'Book the 2-hour Saturday morning slot. Wear old clothes — it gets messy and fun.',
    googleMapsUrl: 'https://maps.google.com/?q=Pottery+Workshop+ECR+Chennai',
    imageKeyword: 'pottery-workshop',
    photoUrl: 'https://images.pexels.com/photos/6611312/pexels-photo-6611312.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=The+Potter\+Chennai',
  },
  {
    id: 'the-art-lounge',
    name: 'The Art Lounge (Painting Sessions)',
    category: 'workshops-classes',
    area: 'Adyar',
    lat: 13.0055,
    lng: 80.2550,
    rating: 4.3,
    reviewCount: 800,
    budget: 'under-2000',
    avgTimeMinutes: 150,
    indoor: true,
    outdoor: false,
    vibes: ['artsy', 'learning', 'chill', 'romantic'],
    groupTypes: ['solo', 'couple', 'friends'],
    openHours: {
      saturday: { open: '10:00', close: '20:00' },
      sunday: { open: '10:00', close: '20:00' },
    },
    description: 'Sip-and-paint sessions, canvas workshops, and guided art classes for all skill levels.',
    insiderTip: 'The Saturday evening sip-and-paint is perfect for a date. No experience needed at all.',
    googleMapsUrl: 'https://maps.google.com/?q=Art+Painting+Class+Adyar+Chennai',
    imageKeyword: 'art-lounge-painting',
    photoUrl: 'https://images.pexels.com/photos/357428/pexels-photo-357428.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=The+Art+Lounge+(Painting+Sessions)+Chennai',
  },
  {
    id: 'cooking-class-mylapore',
    name: 'Authentic Chennai Cooking Class',
    category: 'workshops-classes',
    area: 'Mylapore',
    lat: 13.0360,
    lng: 80.2680,
    rating: 4.6,
    reviewCount: 600,
    budget: 'under-2000',
    avgTimeMinutes: 180,
    indoor: true,
    outdoor: false,
    vibes: ['foodie', 'learning', 'cultural'],
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '09:00', close: '17:00' },
      sunday: { open: '09:00', close: '17:00' },
    },
    description: 'Learn to cook Tamil Nadu classics — dosa, sambar, biryani, filter coffee. Eat everything you make.',
    insiderTip: 'Book the Sunday morning session. You\'ll eat a massive meal of everything you cooked. Worth every rupee.',
    googleMapsUrl: 'https://maps.google.com/?q=Cooking+Class+Mylapore+Chennai',
    imageKeyword: 'cooking-class',
    photoUrl: 'https://images.pexels.com/photos/3531700/pexels-photo-3531700.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    googleSearchUrl: 'https://www.google.com/search?q=Authentic+Chennai+Cooking+Class+Chennai',
  },

  // ===== MORE PHOTOGRAPHY SPOTS =====
  {
    id: 'kapaleeshwarar-gopuram',
    name: 'Kapaleeshwarar Gopuram Viewpoint',
    category: 'photography',
    area: 'Mylapore',
    lat: 13.0340,
    lng: 80.2695,
    rating: 4.5,
    reviewCount: 2800,
    budget: 'free',
    avgTimeMinutes: 30,
    indoor: false,
    outdoor: true,
    vibes: ['cultural', 'artsy'],
    groupTypes: ['solo', 'couple'],
    openHours: {
      saturday: { open: '06:00', close: '20:00' },
      sunday: { open: '06:00', close: '20:00' },
    },
    description: 'The iconic Dravidian gopuram is one of Chennai\'s most photographed structures.',
    insiderTip: 'Best shot from the street opposite during golden hour. The temple tank reflection shot is fire.',
    googleMapsUrl: 'https://maps.google.com/?q=Kapaleeshwarar+Temple+Gopuram+Chennai',
    imageKeyword: 'kapaleeshwarar-gopuram',
    photoUrl: '/api/photo?q=Kapaleeshwarar+Temple+gopuram',
    googleSearchUrl: 'https://www.google.com/search?q=Kapaleeshwarar+Gopuram+Viewpoint+Chennai',
  },
  {
    id: 'light-house',
    name: 'Chennai Lighthouse',
    category: 'photography',
    area: 'Mylapore',
    lat: 13.0400,
    lng: 80.2800,
    rating: 4.1,
    reviewCount: 3500,
    budget: 'under-500',
    avgTimeMinutes: 45,
    indoor: false,
    outdoor: true,
    vibes: ['adventure', 'artsy'],
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    openHours: {
      saturday: { open: '10:00', close: '17:00' },
      sunday: { open: '10:00', close: '17:00' },
    },
    description: 'Climb 140+ steps for a panoramic view of Marina Beach and the Chennai skyline.',
    insiderTip: 'Go around 4 PM for the best light. The view of Marina stretching north is incredible.',
    googleMapsUrl: 'https://maps.google.com/?q=Chennai+Lighthouse',
    imageKeyword: 'chennai-lighthouse',
    photoUrl: '/api/photo?q=Chennai+Lighthouse',
    googleSearchUrl: 'https://www.google.com/search?q=Chennai+Lighthouse+Chennai',
  },
];
